var __defProp = Object.defineProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// src/app.ts
import express6 from "express";
import cors from "cors";

// src/modules/tutorProfile/tutorProfile.route.ts
import express from "express";

// src/lib/prisma.ts
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";

// generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.1",
  "engineVersion": "55ae170b1ced7fc6ed07a15f110549408c501bb3",
  "activeProvider": "postgresql",
  "inlineSchema": 'enum BookingStatus {\n  PENDING\n  APPROVED\n  REJECTED\n}\n\nmodel Booking {\n  id         String        @id @default(uuid())\n  studentId  String\n  tutorId    String\n  categoryId String\n  message    String?\n  date       DateTime?\n  status     BookingStatus @default(PENDING)\n  createdAt  DateTime      @default(now())\n\n  student  User     @relation("StudentBookings", fields: [studentId], references: [id], onDelete: Cascade)\n  tutor    User     @relation("TutorBookings", fields: [tutorId], references: [id], onDelete: Cascade)\n  category Category @relation(fields: [categoryId], references: [id], onDelete: Cascade)\n\n  review Review?\n}\n\nmodel Category {\n  id          String   @id @default(uuid())\n  title       String\n  description String?\n  createdAt   DateTime @default(now())\n\n  bookings Booking[]\n}\n\nmodel Review {\n  id        String   @id @default(uuid())\n  rating    Int\n  comment   String?\n  studentId String\n  tutorId   String\n  bookingId String   @unique\n  createdAt DateTime @default(now())\n\n  student User @relation("StudentReviews", fields: [studentId], references: [id], onDelete: Cascade)\n  tutor   User @relation("TutorReviews", fields: [tutorId], references: [id], onDelete: Cascade)\n\n  booking Booking @relation(fields: [bookingId], references: [id], onDelete: Cascade)\n}\n\n// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel TutorProfile {\n  id     String @id @default(uuid())\n  userId String @unique\n\n  title           String?\n  bio             String?\n  education       String?\n  experienceYears Int?\n  hourlyRate      Int?\n  availability    String?\n\n  rating            Float @default(0)\n  totalReviews      Int   @default(0)\n  totalStudents     Int   @default(0)\n  completedSessions Int   @default(0)\n\n  languages String[]\n  verified  Boolean  @default(false)\n  createdAt DateTime @default(now())\n\n  user User @relation(fields: [userId], references: [id], onDelete: Cascade)\n}\n\nenum Role {\n  ADMIN\n  STUDENT\n  TUTOR\n}\n\nmodel User {\n  id            String   @id\n  name          String\n  email         String   @unique\n  emailVerified Boolean  @default(false)\n  image         String?\n  role          Role     @default(STUDENT)\n  createdAt     DateTime @default(now())\n  updatedAt     DateTime @updatedAt\n\n  sessions Session[]\n  accounts Account[]\n\n  tutorProfile TutorProfile?\n\n  studentBookings Booking[] @relation("StudentBookings")\n  tutorBookings   Booking[] @relation("TutorBookings")\n\n  studentReviews Review[] @relation("StudentReviews")\n  tutorReviews   Review[] @relation("TutorReviews")\n\n  @@map("user")\n}\n\nmodel Session {\n  id        String   @id\n  expiresAt DateTime\n  token     String   @unique\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ipAddress String?\n  userAgent String?\n\n  userId String\n  user   User   @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@index([userId])\n  @@map("session")\n}\n\nmodel Account {\n  id                    String    @id\n  accountId             String\n  providerId            String\n  userId                String\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  password              String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n\n  @@index([userId])\n  @@map("account")\n}\n\nmodel Verification {\n  id         String   @id\n  identifier String\n  value      String\n  expiresAt  DateTime\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"Booking":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"message","kind":"scalar","type":"String"},{"name":"date","kind":"scalar","type":"DateTime"},{"name":"status","kind":"enum","type":"BookingStatus"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"student","kind":"object","type":"User","relationName":"StudentBookings"},{"name":"tutor","kind":"object","type":"User","relationName":"TutorBookings"},{"name":"category","kind":"object","type":"Category","relationName":"BookingToCategory"},{"name":"review","kind":"object","type":"Review","relationName":"BookingToReview"}],"dbName":null},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"title","kind":"scalar","type":"String"},{"name":"description","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"bookings","kind":"object","type":"Booking","relationName":"BookingToCategory"}],"dbName":null},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"studentId","kind":"scalar","type":"String"},{"name":"tutorId","kind":"scalar","type":"String"},{"name":"bookingId","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"student","kind":"object","type":"User","relationName":"StudentReviews"},{"name":"tutor","kind":"object","type":"User","relationName":"TutorReviews"},{"name":"booking","kind":"object","type":"Booking","relationName":"BookingToReview"}],"dbName":null},"TutorProfile":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"title","kind":"scalar","type":"String"},{"name":"bio","kind":"scalar","type":"String"},{"name":"education","kind":"scalar","type":"String"},{"name":"experienceYears","kind":"scalar","type":"Int"},{"name":"hourlyRate","kind":"scalar","type":"Int"},{"name":"availability","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Float"},{"name":"totalReviews","kind":"scalar","type":"Int"},{"name":"totalStudents","kind":"scalar","type":"Int"},{"name":"completedSessions","kind":"scalar","type":"Int"},{"name":"languages","kind":"scalar","type":"String"},{"name":"verified","kind":"scalar","type":"Boolean"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"user","kind":"object","type":"User","relationName":"TutorProfileToUser"}],"dbName":null},"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"image","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"Role"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"},{"name":"tutorProfile","kind":"object","type":"TutorProfile","relationName":"TutorProfileToUser"},{"name":"studentBookings","kind":"object","type":"Booking","relationName":"StudentBookings"},{"name":"tutorBookings","kind":"object","type":"Booking","relationName":"TutorBookings"},{"name":"studentReviews","kind":"object","type":"Review","relationName":"StudentReviews"},{"name":"tutorReviews","kind":"object","type":"Review","relationName":"TutorReviews"}],"dbName":"user"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"}],"dbName":"session"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"account"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","user","sessions","accounts","tutorProfile","studentBookings","tutorBookings","student","tutor","booking","studentReviews","tutorReviews","_count","bookings","category","review","Booking.findUnique","Booking.findUniqueOrThrow","Booking.findFirst","Booking.findFirstOrThrow","Booking.findMany","data","Booking.createOne","Booking.createMany","Booking.createManyAndReturn","Booking.updateOne","Booking.updateMany","Booking.updateManyAndReturn","create","update","Booking.upsertOne","Booking.deleteOne","Booking.deleteMany","having","_min","_max","Booking.groupBy","Booking.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","_avg","_sum","Review.groupBy","Review.aggregate","TutorProfile.findUnique","TutorProfile.findUniqueOrThrow","TutorProfile.findFirst","TutorProfile.findFirstOrThrow","TutorProfile.findMany","TutorProfile.createOne","TutorProfile.createMany","TutorProfile.createManyAndReturn","TutorProfile.updateOne","TutorProfile.updateMany","TutorProfile.updateManyAndReturn","TutorProfile.upsertOne","TutorProfile.deleteOne","TutorProfile.deleteMany","TutorProfile.groupBy","TutorProfile.aggregate","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","User.upsertOne","User.deleteOne","User.deleteMany","User.groupBy","User.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","AND","OR","NOT","id","identifier","value","expiresAt","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","accountId","providerId","userId","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","password","token","ipAddress","userAgent","name","email","emailVerified","image","Role","role","every","some","none","title","bio","education","experienceYears","hourlyRate","availability","rating","totalReviews","totalStudents","completedSessions","languages","verified","has","hasEvery","hasSome","comment","studentId","tutorId","bookingId","description","categoryId","message","date","BookingStatus","status","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","push","increment","decrement","multiply","divide"]'),
  graph: "-gNHgAEPCQAAiwIAIAoAAIsCACAQAACYAgAgEQAAmQIAIJoBAACVAgAwmwEAAA0AEJwBAACVAgAwnQEBAAAAAaEBQADjAQAh1AEBAOIBACHVAQEA4gEAIdgBAQDiAQAh2QEBAPYBACHaAUAAlgIAIdwBAACXAtwBIgEAAAABACAMAwAAiwIAIJoBAACbAgAwmwEAAAMAEJwBAACbAgAwnQEBAOIBACGgAUAA4wEAIaEBQADjAQAhogFAAOMBACGwAQEA4gEAIbgBAQDiAQAhuQEBAPYBACG6AQEA9gEAIQMDAACtAwAguQEAAKECACC6AQAAoQIAIAwDAACLAgAgmgEAAJsCADCbAQAAAwAQnAEAAJsCADCdAQEAAAABoAFAAOMBACGhAUAA4wEAIaIBQADjAQAhsAEBAOIBACG4AQEAAAABuQEBAPYBACG6AQEA9gEAIQMAAAADACABAAAEADACAAAFACARAwAAiwIAIJoBAACaAgAwmwEAAAcAEJwBAACaAgAwnQEBAOIBACGhAUAA4wEAIaIBQADjAQAhrgEBAOIBACGvAQEA4gEAIbABAQDiAQAhsQEBAPYBACGyAQEA9gEAIbMBAQD2AQAhtAFAAJYCACG1AUAAlgIAIbYBAQD2AQAhtwEBAPYBACEIAwAArQMAILEBAAChAgAgsgEAAKECACCzAQAAoQIAILQBAAChAgAgtQEAAKECACC2AQAAoQIAILcBAAChAgAgEQMAAIsCACCaAQAAmgIAMJsBAAAHABCcAQAAmgIAMJ0BAQAAAAGhAUAA4wEAIaIBQADjAQAhrgEBAOIBACGvAQEA4gEAIbABAQDiAQAhsQEBAPYBACGyAQEA9gEAIbMBAQD2AQAhtAFAAJYCACG1AUAAlgIAIbYBAQD2AQAhtwEBAPYBACEDAAAABwAgAQAACAAwAgAACQAgEwMAAIsCACCaAQAAhwIAMJsBAAALABCcAQAAhwIAMJ0BAQDiAQAhoQFAAOMBACGwAQEA4gEAIcQBAQD2AQAhxQEBAPYBACHGAQEA9gEAIccBAgCIAgAhyAECAIgCACHJAQEA9gEAIcoBCACJAgAhywECAIoCACHMAQIAigIAIc0BAgCKAgAhzgEAAIECACDPASAA9QEAIQEAAAALACAPCQAAiwIAIAoAAIsCACAQAACYAgAgEQAAmQIAIJoBAACVAgAwmwEAAA0AEJwBAACVAgAwnQEBAOIBACGhAUAA4wEAIdQBAQDiAQAh1QEBAOIBACHYAQEA4gEAIdkBAQD2AQAh2gFAAJYCACHcAQAAlwLcASIGCQAArQMAIAoAAK0DACAQAADFAwAgEQAAxgMAINkBAAChAgAg2gEAAKECACADAAAADQAgAQAADgAwAgAAAQAgAwAAAA0AIAEAAA4AMAIAAAEAIA0JAACLAgAgCgAAiwIAIAsAAJQCACCaAQAAkwIAMJsBAAARABCcAQAAkwIAMJ0BAQDiAQAhoQFAAOMBACHKAQIAigIAIdMBAQD2AQAh1AEBAOIBACHVAQEA4gEAIdYBAQDiAQAhBAkAAK0DACAKAACtAwAgCwAAxAMAINMBAAChAgAgDQkAAIsCACAKAACLAgAgCwAAlAIAIJoBAACTAgAwmwEAABEAEJwBAACTAgAwnQEBAAAAAaEBQADjAQAhygECAIoCACHTAQEA9gEAIdQBAQDiAQAh1QEBAOIBACHWAQEAAAABAwAAABEAIAEAABIAMAIAABMAIAMAAAARACABAAASADACAAATACABAAAAAwAgAQAAAAcAIAEAAAANACABAAAADQAgAQAAABEAIAEAAAARACADAAAADQAgAQAADgAwAgAAAQAgAQAAAA0AIAEAAAARACABAAAAAQAgAwAAAA0AIAEAAA4AMAIAAAEAIAMAAAANACABAAAOADACAAABACADAAAADQAgAQAADgAwAgAAAQAgDAkAAOsCACAKAAD4AgAgEAAA7AIAIBEAAO0CACCdAQEAAAABoQFAAAAAAdQBAQAAAAHVAQEAAAAB2AEBAAAAAdkBAQAAAAHaAUAAAAAB3AEAAADcAQIBFwAAIwAgCJ0BAQAAAAGhAUAAAAAB1AEBAAAAAdUBAQAAAAHYAQEAAAAB2QEBAAAAAdoBQAAAAAHcAQAAANwBAgEXAAAlADABFwAAJQAwDAkAAOICACAKAAD2AgAgEAAA4wIAIBEAAOQCACCdAQEAnwIAIaEBQACgAgAh1AEBAJ8CACHVAQEAnwIAIdgBAQCfAgAh2QEBAKUCACHaAUAApgIAIdwBAADgAtwBIgIAAAABACAXAAAoACAInQEBAJ8CACGhAUAAoAIAIdQBAQCfAgAh1QEBAJ8CACHYAQEAnwIAIdkBAQClAgAh2gFAAKYCACHcAQAA4ALcASICAAAADQAgFwAAKgAgAgAAAA0AIBcAACoAIAMAAAABACAeAAAjACAfAAAoACABAAAAAQAgAQAAAA0AIAUOAADBAwAgJAAAwwMAICUAAMIDACDZAQAAoQIAINoBAAChAgAgC5oBAACPAgAwmwEAADEAEJwBAACPAgAwnQEBANoBACGhAUAA2wEAIdQBAQDaAQAh1QEBANoBACHYAQEA2gEAIdkBAQDlAQAh2gFAAOYBACHcAQAAkALcASIDAAAADQAgAQAAMAAwIwAAMQAgAwAAAA0AIAEAAA4AMAIAAAEAIAgPAAD7AQAgmgEAAI4CADCbAQAANwAQnAEAAI4CADCdAQEAAAABoQFAAOMBACHEAQEA4gEAIdcBAQD2AQAhAQAAADQAIAEAAAA0ACAIDwAA-wEAIJoBAACOAgAwmwEAADcAEJwBAACOAgAwnQEBAOIBACGhAUAA4wEAIcQBAQDiAQAh1wEBAPYBACECDwAApAMAINcBAAChAgAgAwAAADcAIAEAADgAMAIAADQAIAMAAAA3ACABAAA4ADACAAA0ACADAAAANwAgAQAAOAAwAgAANAAgBQ8AAMADACCdAQEAAAABoQFAAAAAAcQBAQAAAAHXAQEAAAABARcAADwAIASdAQEAAAABoQFAAAAAAcQBAQAAAAHXAQEAAAABARcAAD4AMAEXAAA-ADAFDwAAtgMAIJ0BAQCfAgAhoQFAAKACACHEAQEAnwIAIdcBAQClAgAhAgAAADQAIBcAAEEAIASdAQEAnwIAIaEBQACgAgAhxAEBAJ8CACHXAQEApQIAIQIAAAA3ACAXAABDACACAAAANwAgFwAAQwAgAwAAADQAIB4AADwAIB8AAEEAIAEAAAA0ACABAAAANwAgBA4AALMDACAkAAC1AwAgJQAAtAMAINcBAAChAgAgB5oBAACNAgAwmwEAAEoAEJwBAACNAgAwnQEBANoBACGhAUAA2wEAIcQBAQDaAQAh1wEBAOUBACEDAAAANwAgAQAASQAwIwAASgAgAwAAADcAIAEAADgAMAIAADQAIAEAAAATACABAAAAEwAgAwAAABEAIAEAABIAMAIAABMAIAMAAAARACABAAASADACAAATACADAAAAEQAgAQAAEgAwAgAAEwAgCgkAAMkCACAKAADVAgAgCwAAygIAIJ0BAQAAAAGhAUAAAAABygECAAAAAdMBAQAAAAHUAQEAAAAB1QEBAAAAAdYBAQAAAAEBFwAAUgAgB50BAQAAAAGhAUAAAAABygECAAAAAdMBAQAAAAHUAQEAAAAB1QEBAAAAAdYBAQAAAAEBFwAAVAAwARcAAFQAMAoJAADGAgAgCgAA0wIAIAsAAMcCACCdAQEAnwIAIaEBQACgAgAhygECAMQCACHTAQEApQIAIdQBAQCfAgAh1QEBAJ8CACHWAQEAnwIAIQIAAAATACAXAABXACAHnQEBAJ8CACGhAUAAoAIAIcoBAgDEAgAh0wEBAKUCACHUAQEAnwIAIdUBAQCfAgAh1gEBAJ8CACECAAAAEQAgFwAAWQAgAgAAABEAIBcAAFkAIAMAAAATACAeAABSACAfAABXACABAAAAEwAgAQAAABEAIAYOAACuAwAgJAAAsQMAICUAALADACBGAACvAwAgRwAAsgMAINMBAAChAgAgCpoBAACMAgAwmwEAAGAAEJwBAACMAgAwnQEBANoBACGhAUAA2wEAIcoBAgCAAgAh0wEBAOUBACHUAQEA2gEAIdUBAQDaAQAh1gEBANoBACEDAAAAEQAgAQAAXwAwIwAAYAAgAwAAABEAIAEAABIAMAIAABMAIBMDAACLAgAgmgEAAIcCADCbAQAACwAQnAEAAIcCADCdAQEAAAABoQFAAOMBACGwAQEAAAABxAEBAPYBACHFAQEA9gEAIcYBAQD2AQAhxwECAIgCACHIAQIAiAIAIckBAQD2AQAhygEIAIkCACHLAQIAigIAIcwBAgCKAgAhzQECAIoCACHOAQAAgQIAIM8BIAD1AQAhAQAAAGMAIAEAAABjACAHAwAArQMAIMQBAAChAgAgxQEAAKECACDGAQAAoQIAIMcBAAChAgAgyAEAAKECACDJAQAAoQIAIAMAAAALACABAABmADACAABjACADAAAACwAgAQAAZgAwAgAAYwAgAwAAAAsAIAEAAGYAMAIAAGMAIBADAACsAwAgnQEBAAAAAaEBQAAAAAGwAQEAAAABxAEBAAAAAcUBAQAAAAHGAQEAAAABxwECAAAAAcgBAgAAAAHJAQEAAAABygEIAAAAAcsBAgAAAAHMAQIAAAABzQECAAAAAc4BAACBAwAgzwEgAAAAAQEXAABqACAPnQEBAAAAAaEBQAAAAAGwAQEAAAABxAEBAAAAAcUBAQAAAAHGAQEAAAABxwECAAAAAcgBAgAAAAHJAQEAAAABygEIAAAAAcsBAgAAAAHMAQIAAAABzQECAAAAAc4BAACBAwAgzwEgAAAAAQEXAABsADABFwAAbAAwEAMAAKsDACCdAQEAnwIAIaEBQACgAgAhsAEBAJ8CACHEAQEApQIAIcUBAQClAgAhxgEBAKUCACHHAQIA_gIAIcgBAgD-AgAhyQEBAKUCACHKAQgA_wIAIcsBAgDEAgAhzAECAMQCACHNAQIAxAIAIc4BAACAAwAgzwEgALECACECAAAAYwAgFwAAbwAgD50BAQCfAgAhoQFAAKACACGwAQEAnwIAIcQBAQClAgAhxQEBAKUCACHGAQEApQIAIccBAgD-AgAhyAECAP4CACHJAQEApQIAIcoBCAD_AgAhywECAMQCACHMAQIAxAIAIc0BAgDEAgAhzgEAAIADACDPASAAsQIAIQIAAAALACAXAABxACACAAAACwAgFwAAcQAgAwAAAGMAIB4AAGoAIB8AAG8AIAEAAABjACABAAAACwAgCw4AAKYDACAkAACpAwAgJQAAqAMAIEYAAKcDACBHAACqAwAgxAEAAKECACDFAQAAoQIAIMYBAAChAgAgxwEAAKECACDIAQAAoQIAIMkBAAChAgAgEpoBAAD9AQAwmwEAAHgAEJwBAAD9AQAwnQEBANoBACGhAUAA2wEAIbABAQDaAQAhxAEBAOUBACHFAQEA5QEAIcYBAQDlAQAhxwECAP4BACHIAQIA_gEAIckBAQDlAQAhygEIAP8BACHLAQIAgAIAIcwBAgCAAgAhzQECAIACACHOAQAAgQIAIM8BIADuAQAhAwAAAAsAIAEAAHcAMCMAAHgAIAMAAAALACABAABmADACAABjACASBAAA-AEAIAUAAPkBACAGAAD6AQAgBwAA-wEAIAgAAPsBACAMAAD8AQAgDQAA_AEAIJoBAAD0AQAwmwEAAH4AEJwBAAD0AQAwnQEBAAAAAaEBQADjAQAhogFAAOMBACG7AQEA4gEAIbwBAQAAAAG9ASAA9QEAIb4BAQD2AQAhwAEAAPcBwAEiAQAAAHsAIAEAAAB7ACASBAAA-AEAIAUAAPkBACAGAAD6AQAgBwAA-wEAIAgAAPsBACAMAAD8AQAgDQAA_AEAIJoBAAD0AQAwmwEAAH4AEJwBAAD0AQAwnQEBAOIBACGhAUAA4wEAIaIBQADjAQAhuwEBAOIBACG8AQEA4gEAIb0BIAD1AQAhvgEBAPYBACHAAQAA9wHAASIIBAAAoQMAIAUAAKIDACAGAACjAwAgBwAApAMAIAgAAKQDACAMAAClAwAgDQAApQMAIL4BAAChAgAgAwAAAH4AIAEAAH8AMAIAAHsAIAMAAAB-ACABAAB_ADACAAB7ACADAAAAfgAgAQAAfwAwAgAAewAgDwQAAJoDACAFAACbAwAgBgAAnAMAIAcAAJ0DACAIAACeAwAgDAAAnwMAIA0AAKADACCdAQEAAAABoQFAAAAAAaIBQAAAAAG7AQEAAAABvAEBAAAAAb0BIAAAAAG-AQEAAAABwAEAAADAAQIBFwAAgwEAIAidAQEAAAABoQFAAAAAAaIBQAAAAAG7AQEAAAABvAEBAAAAAb0BIAAAAAG-AQEAAAABwAEAAADAAQIBFwAAhQEAMAEXAACFAQAwDwQAALMCACAFAAC0AgAgBgAAtQIAIAcAALYCACAIAAC3AgAgDAAAuAIAIA0AALkCACCdAQEAnwIAIaEBQACgAgAhogFAAKACACG7AQEAnwIAIbwBAQCfAgAhvQEgALECACG-AQEApQIAIcABAACyAsABIgIAAAB7ACAXAACIAQAgCJ0BAQCfAgAhoQFAAKACACGiAUAAoAIAIbsBAQCfAgAhvAEBAJ8CACG9ASAAsQIAIb4BAQClAgAhwAEAALICwAEiAgAAAH4AIBcAAIoBACACAAAAfgAgFwAAigEAIAMAAAB7ACAeAACDAQAgHwAAiAEAIAEAAAB7ACABAAAAfgAgBA4AAK4CACAkAACwAgAgJQAArwIAIL4BAAChAgAgC5oBAADtAQAwmwEAAJEBABCcAQAA7QEAMJ0BAQDaAQAhoQFAANsBACGiAUAA2wEAIbsBAQDaAQAhvAEBANoBACG9ASAA7gEAIb4BAQDlAQAhwAEAAO8BwAEiAwAAAH4AIAEAAJABADAjAACRAQAgAwAAAH4AIAEAAH8AMAIAAHsAIAEAAAAFACABAAAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAMAAAADACABAAAEADACAAAFACADAAAAAwAgAQAABAAwAgAABQAgCQMAAK0CACCdAQEAAAABoAFAAAAAAaEBQAAAAAGiAUAAAAABsAEBAAAAAbgBAQAAAAG5AQEAAAABugEBAAAAAQEXAACZAQAgCJ0BAQAAAAGgAUAAAAABoQFAAAAAAaIBQAAAAAGwAQEAAAABuAEBAAAAAbkBAQAAAAG6AQEAAAABARcAAJsBADABFwAAmwEAMAkDAACsAgAgnQEBAJ8CACGgAUAAoAIAIaEBQACgAgAhogFAAKACACGwAQEAnwIAIbgBAQCfAgAhuQEBAKUCACG6AQEApQIAIQIAAAAFACAXAACeAQAgCJ0BAQCfAgAhoAFAAKACACGhAUAAoAIAIaIBQACgAgAhsAEBAJ8CACG4AQEAnwIAIbkBAQClAgAhugEBAKUCACECAAAAAwAgFwAAoAEAIAIAAAADACAXAACgAQAgAwAAAAUAIB4AAJkBACAfAACeAQAgAQAAAAUAIAEAAAADACAFDgAAqQIAICQAAKsCACAlAACqAgAguQEAAKECACC6AQAAoQIAIAuaAQAA7AEAMJsBAACnAQAQnAEAAOwBADCdAQEA2gEAIaABQADbAQAhoQFAANsBACGiAUAA2wEAIbABAQDaAQAhuAEBANoBACG5AQEA5QEAIboBAQDlAQAhAwAAAAMAIAEAAKYBADAjAACnAQAgAwAAAAMAIAEAAAQAMAIAAAUAIAEAAAAJACABAAAACQAgAwAAAAcAIAEAAAgAMAIAAAkAIAMAAAAHACABAAAIADACAAAJACADAAAABwAgAQAACAAwAgAACQAgDgMAAKgCACCdAQEAAAABoQFAAAAAAaIBQAAAAAGuAQEAAAABrwEBAAAAAbABAQAAAAGxAQEAAAABsgEBAAAAAbMBAQAAAAG0AUAAAAABtQFAAAAAAbYBAQAAAAG3AQEAAAABARcAAK8BACANnQEBAAAAAaEBQAAAAAGiAUAAAAABrgEBAAAAAa8BAQAAAAGwAQEAAAABsQEBAAAAAbIBAQAAAAGzAQEAAAABtAFAAAAAAbUBQAAAAAG2AQEAAAABtwEBAAAAAQEXAACxAQAwARcAALEBADAOAwAApwIAIJ0BAQCfAgAhoQFAAKACACGiAUAAoAIAIa4BAQCfAgAhrwEBAJ8CACGwAQEAnwIAIbEBAQClAgAhsgEBAKUCACGzAQEApQIAIbQBQACmAgAhtQFAAKYCACG2AQEApQIAIbcBAQClAgAhAgAAAAkAIBcAALQBACANnQEBAJ8CACGhAUAAoAIAIaIBQACgAgAhrgEBAJ8CACGvAQEAnwIAIbABAQCfAgAhsQEBAKUCACGyAQEApQIAIbMBAQClAgAhtAFAAKYCACG1AUAApgIAIbYBAQClAgAhtwEBAKUCACECAAAABwAgFwAAtgEAIAIAAAAHACAXAAC2AQAgAwAAAAkAIB4AAK8BACAfAAC0AQAgAQAAAAkAIAEAAAAHACAKDgAAogIAICQAAKQCACAlAACjAgAgsQEAAKECACCyAQAAoQIAILMBAAChAgAgtAEAAKECACC1AQAAoQIAILYBAAChAgAgtwEAAKECACAQmgEAAOQBADCbAQAAvQEAEJwBAADkAQAwnQEBANoBACGhAUAA2wEAIaIBQADbAQAhrgEBANoBACGvAQEA2gEAIbABAQDaAQAhsQEBAOUBACGyAQEA5QEAIbMBAQDlAQAhtAFAAOYBACG1AUAA5gEAIbYBAQDlAQAhtwEBAOUBACEDAAAABwAgAQAAvAEAMCMAAL0BACADAAAABwAgAQAACAAwAgAACQAgCZoBAADhAQAwmwEAAMMBABCcAQAA4QEAMJ0BAQAAAAGeAQEA4gEAIZ8BAQDiAQAhoAFAAOMBACGhAUAA4wEAIaIBQADjAQAhAQAAAMABACABAAAAwAEAIAmaAQAA4QEAMJsBAADDAQAQnAEAAOEBADCdAQEA4gEAIZ4BAQDiAQAhnwEBAOIBACGgAUAA4wEAIaEBQADjAQAhogFAAOMBACEAAwAAAMMBACABAADEAQAwAgAAwAEAIAMAAADDAQAgAQAAxAEAMAIAAMABACADAAAAwwEAIAEAAMQBADACAADAAQAgBp0BAQAAAAGeAQEAAAABnwEBAAAAAaABQAAAAAGhAUAAAAABogFAAAAAAQEXAADIAQAgBp0BAQAAAAGeAQEAAAABnwEBAAAAAaABQAAAAAGhAUAAAAABogFAAAAAAQEXAADKAQAwARcAAMoBADAGnQEBAJ8CACGeAQEAnwIAIZ8BAQCfAgAhoAFAAKACACGhAUAAoAIAIaIBQACgAgAhAgAAAMABACAXAADNAQAgBp0BAQCfAgAhngEBAJ8CACGfAQEAnwIAIaABQACgAgAhoQFAAKACACGiAUAAoAIAIQIAAADDAQAgFwAAzwEAIAIAAADDAQAgFwAAzwEAIAMAAADAAQAgHgAAyAEAIB8AAM0BACABAAAAwAEAIAEAAADDAQAgAw4AAJwCACAkAACeAgAgJQAAnQIAIAmaAQAA2QEAMJsBAADWAQAQnAEAANkBADCdAQEA2gEAIZ4BAQDaAQAhnwEBANoBACGgAUAA2wEAIaEBQADbAQAhogFAANsBACEDAAAAwwEAIAEAANUBADAjAADWAQAgAwAAAMMBACABAADEAQAwAgAAwAEAIAmaAQAA2QEAMJsBAADWAQAQnAEAANkBADCdAQEA2gEAIZ4BAQDaAQAhnwEBANoBACGgAUAA2wEAIaEBQADbAQAhogFAANsBACEODgAA3QEAICQAAOABACAlAADgAQAgowEBAAAAAaQBAQAAAASlAQEAAAAEpgEBAAAAAacBAQAAAAGoAQEAAAABqQEBAAAAAaoBAQDfAQAhqwEBAAAAAawBAQAAAAGtAQEAAAABCw4AAN0BACAkAADeAQAgJQAA3gEAIKMBQAAAAAGkAUAAAAAEpQFAAAAABKYBQAAAAAGnAUAAAAABqAFAAAAAAakBQAAAAAGqAUAA3AEAIQsOAADdAQAgJAAA3gEAICUAAN4BACCjAUAAAAABpAFAAAAABKUBQAAAAASmAUAAAAABpwFAAAAAAagBQAAAAAGpAUAAAAABqgFAANwBACEIowECAAAAAaQBAgAAAASlAQIAAAAEpgECAAAAAacBAgAAAAGoAQIAAAABqQECAAAAAaoBAgDdAQAhCKMBQAAAAAGkAUAAAAAEpQFAAAAABKYBQAAAAAGnAUAAAAABqAFAAAAAAakBQAAAAAGqAUAA3gEAIQ4OAADdAQAgJAAA4AEAICUAAOABACCjAQEAAAABpAEBAAAABKUBAQAAAASmAQEAAAABpwEBAAAAAagBAQAAAAGpAQEAAAABqgEBAN8BACGrAQEAAAABrAEBAAAAAa0BAQAAAAELowEBAAAAAaQBAQAAAASlAQEAAAAEpgEBAAAAAacBAQAAAAGoAQEAAAABqQEBAAAAAaoBAQDgAQAhqwEBAAAAAawBAQAAAAGtAQEAAAABCZoBAADhAQAwmwEAAMMBABCcAQAA4QEAMJ0BAQDiAQAhngEBAOIBACGfAQEA4gEAIaABQADjAQAhoQFAAOMBACGiAUAA4wEAIQujAQEAAAABpAEBAAAABKUBAQAAAASmAQEAAAABpwEBAAAAAagBAQAAAAGpAQEAAAABqgEBAOABACGrAQEAAAABrAEBAAAAAa0BAQAAAAEIowFAAAAAAaQBQAAAAASlAUAAAAAEpgFAAAAAAacBQAAAAAGoAUAAAAABqQFAAAAAAaoBQADeAQAhEJoBAADkAQAwmwEAAL0BABCcAQAA5AEAMJ0BAQDaAQAhoQFAANsBACGiAUAA2wEAIa4BAQDaAQAhrwEBANoBACGwAQEA2gEAIbEBAQDlAQAhsgEBAOUBACGzAQEA5QEAIbQBQADmAQAhtQFAAOYBACG2AQEA5QEAIbcBAQDlAQAhDg4AAOgBACAkAADrAQAgJQAA6wEAIKMBAQAAAAGkAQEAAAAFpQEBAAAABaYBAQAAAAGnAQEAAAABqAEBAAAAAakBAQAAAAGqAQEA6gEAIasBAQAAAAGsAQEAAAABrQEBAAAAAQsOAADoAQAgJAAA6QEAICUAAOkBACCjAUAAAAABpAFAAAAABaUBQAAAAAWmAUAAAAABpwFAAAAAAagBQAAAAAGpAUAAAAABqgFAAOcBACELDgAA6AEAICQAAOkBACAlAADpAQAgowFAAAAAAaQBQAAAAAWlAUAAAAAFpgFAAAAAAacBQAAAAAGoAUAAAAABqQFAAAAAAaoBQADnAQAhCKMBAgAAAAGkAQIAAAAFpQECAAAABaYBAgAAAAGnAQIAAAABqAECAAAAAakBAgAAAAGqAQIA6AEAIQijAUAAAAABpAFAAAAABaUBQAAAAAWmAUAAAAABpwFAAAAAAagBQAAAAAGpAUAAAAABqgFAAOkBACEODgAA6AEAICQAAOsBACAlAADrAQAgowEBAAAAAaQBAQAAAAWlAQEAAAAFpgEBAAAAAacBAQAAAAGoAQEAAAABqQEBAAAAAaoBAQDqAQAhqwEBAAAAAawBAQAAAAGtAQEAAAABC6MBAQAAAAGkAQEAAAAFpQEBAAAABaYBAQAAAAGnAQEAAAABqAEBAAAAAakBAQAAAAGqAQEA6wEAIasBAQAAAAGsAQEAAAABrQEBAAAAAQuaAQAA7AEAMJsBAACnAQAQnAEAAOwBADCdAQEA2gEAIaABQADbAQAhoQFAANsBACGiAUAA2wEAIbABAQDaAQAhuAEBANoBACG5AQEA5QEAIboBAQDlAQAhC5oBAADtAQAwmwEAAJEBABCcAQAA7QEAMJ0BAQDaAQAhoQFAANsBACGiAUAA2wEAIbsBAQDaAQAhvAEBANoBACG9ASAA7gEAIb4BAQDlAQAhwAEAAO8BwAEiBQ4AAN0BACAkAADzAQAgJQAA8wEAIKMBIAAAAAGqASAA8gEAIQcOAADdAQAgJAAA8QEAICUAAPEBACCjAQAAAMABAqQBAAAAwAEIpQEAAADAAQiqAQAA8AHAASIHDgAA3QEAICQAAPEBACAlAADxAQAgowEAAADAAQKkAQAAAMABCKUBAAAAwAEIqgEAAPABwAEiBKMBAAAAwAECpAEAAADAAQilAQAAAMABCKoBAADxAcABIgUOAADdAQAgJAAA8wEAICUAAPMBACCjASAAAAABqgEgAPIBACECowEgAAAAAaoBIADzAQAhEgQAAPgBACAFAAD5AQAgBgAA-gEAIAcAAPsBACAIAAD7AQAgDAAA_AEAIA0AAPwBACCaAQAA9AEAMJsBAAB-ABCcAQAA9AEAMJ0BAQDiAQAhoQFAAOMBACGiAUAA4wEAIbsBAQDiAQAhvAEBAOIBACG9ASAA9QEAIb4BAQD2AQAhwAEAAPcBwAEiAqMBIAAAAAGqASAA8wEAIQujAQEAAAABpAEBAAAABaUBAQAAAAWmAQEAAAABpwEBAAAAAagBAQAAAAGpAQEAAAABqgEBAOsBACGrAQEAAAABrAEBAAAAAa0BAQAAAAEEowEAAADAAQKkAQAAAMABCKUBAAAAwAEIqgEAAPEBwAEiA8EBAAADACDCAQAAAwAgwwEAAAMAIAPBAQAABwAgwgEAAAcAIMMBAAAHACAVAwAAiwIAIJoBAACHAgAwmwEAAAsAEJwBAACHAgAwnQEBAOIBACGhAUAA4wEAIbABAQDiAQAhxAEBAPYBACHFAQEA9gEAIcYBAQD2AQAhxwECAIgCACHIAQIAiAIAIckBAQD2AQAhygEIAIkCACHLAQIAigIAIcwBAgCKAgAhzQECAIoCACHOAQAAgQIAIM8BIAD1AQAh3QEAAAsAIN4BAAALACADwQEAAA0AIMIBAAANACDDAQAADQAgA8EBAAARACDCAQAAEQAgwwEAABEAIBKaAQAA_QEAMJsBAAB4ABCcAQAA_QEAMJ0BAQDaAQAhoQFAANsBACGwAQEA2gEAIcQBAQDlAQAhxQEBAOUBACHGAQEA5QEAIccBAgD-AQAhyAECAP4BACHJAQEA5QEAIcoBCAD_AQAhywECAIACACHMAQIAgAIAIc0BAgCAAgAhzgEAAIECACDPASAA7gEAIQ0OAADoAQAgJAAA6AEAICUAAOgBACBGAACGAgAgRwAA6AEAIKMBAgAAAAGkAQIAAAAFpQECAAAABaYBAgAAAAGnAQIAAAABqAECAAAAAakBAgAAAAGqAQIAhQIAIQ0OAADdAQAgJAAAgwIAICUAAIMCACBGAACDAgAgRwAAgwIAIKMBCAAAAAGkAQgAAAAEpQEIAAAABKYBCAAAAAGnAQgAAAABqAEIAAAAAakBCAAAAAGqAQgAhAIAIQ0OAADdAQAgJAAA3QEAICUAAN0BACBGAACDAgAgRwAA3QEAIKMBAgAAAAGkAQIAAAAEpQECAAAABKYBAgAAAAGnAQIAAAABqAECAAAAAakBAgAAAAGqAQIAggIAIQSjAQEAAAAF0AEBAAAAAdEBAQAAAATSAQEAAAAEDQ4AAN0BACAkAADdAQAgJQAA3QEAIEYAAIMCACBHAADdAQAgowECAAAAAaQBAgAAAASlAQIAAAAEpgECAAAAAacBAgAAAAGoAQIAAAABqQECAAAAAaoBAgCCAgAhCKMBCAAAAAGkAQgAAAAEpQEIAAAABKYBCAAAAAGnAQgAAAABqAEIAAAAAakBCAAAAAGqAQgAgwIAIQ0OAADdAQAgJAAAgwIAICUAAIMCACBGAACDAgAgRwAAgwIAIKMBCAAAAAGkAQgAAAAEpQEIAAAABKYBCAAAAAGnAQgAAAABqAEIAAAAAakBCAAAAAGqAQgAhAIAIQ0OAADoAQAgJAAA6AEAICUAAOgBACBGAACGAgAgRwAA6AEAIKMBAgAAAAGkAQIAAAAFpQECAAAABaYBAgAAAAGnAQIAAAABqAECAAAAAakBAgAAAAGqAQIAhQIAIQijAQgAAAABpAEIAAAABaUBCAAAAAWmAQgAAAABpwEIAAAAAagBCAAAAAGpAQgAAAABqgEIAIYCACETAwAAiwIAIJoBAACHAgAwmwEAAAsAEJwBAACHAgAwnQEBAOIBACGhAUAA4wEAIbABAQDiAQAhxAEBAPYBACHFAQEA9gEAIcYBAQD2AQAhxwECAIgCACHIAQIAiAIAIckBAQD2AQAhygEIAIkCACHLAQIAigIAIcwBAgCKAgAhzQECAIoCACHOAQAAgQIAIM8BIAD1AQAhCKMBAgAAAAGkAQIAAAAFpQECAAAABaYBAgAAAAGnAQIAAAABqAECAAAAAakBAgAAAAGqAQIA6AEAIQijAQgAAAABpAEIAAAABKUBCAAAAASmAQgAAAABpwEIAAAAAagBCAAAAAGpAQgAAAABqgEIAIMCACEIowECAAAAAaQBAgAAAASlAQIAAAAEpgECAAAAAacBAgAAAAGoAQIAAAABqQECAAAAAaoBAgDdAQAhFAQAAPgBACAFAAD5AQAgBgAA-gEAIAcAAPsBACAIAAD7AQAgDAAA_AEAIA0AAPwBACCaAQAA9AEAMJsBAAB-ABCcAQAA9AEAMJ0BAQDiAQAhoQFAAOMBACGiAUAA4wEAIbsBAQDiAQAhvAEBAOIBACG9ASAA9QEAIb4BAQD2AQAhwAEAAPcBwAEi3QEAAH4AIN4BAAB-ACAKmgEAAIwCADCbAQAAYAAQnAEAAIwCADCdAQEA2gEAIaEBQADbAQAhygECAIACACHTAQEA5QEAIdQBAQDaAQAh1QEBANoBACHWAQEA2gEAIQeaAQAAjQIAMJsBAABKABCcAQAAjQIAMJ0BAQDaAQAhoQFAANsBACHEAQEA2gEAIdcBAQDlAQAhCA8AAPsBACCaAQAAjgIAMJsBAAA3ABCcAQAAjgIAMJ0BAQDiAQAhoQFAAOMBACHEAQEA4gEAIdcBAQD2AQAhC5oBAACPAgAwmwEAADEAEJwBAACPAgAwnQEBANoBACGhAUAA2wEAIdQBAQDaAQAh1QEBANoBACHYAQEA2gEAIdkBAQDlAQAh2gFAAOYBACHcAQAAkALcASIHDgAA3QEAICQAAJICACAlAACSAgAgowEAAADcAQKkAQAAANwBCKUBAAAA3AEIqgEAAJEC3AEiBw4AAN0BACAkAACSAgAgJQAAkgIAIKMBAAAA3AECpAEAAADcAQilAQAAANwBCKoBAACRAtwBIgSjAQAAANwBAqQBAAAA3AEIpQEAAADcAQiqAQAAkgLcASINCQAAiwIAIAoAAIsCACALAACUAgAgmgEAAJMCADCbAQAAEQAQnAEAAJMCADCdAQEA4gEAIaEBQADjAQAhygECAIoCACHTAQEA9gEAIdQBAQDiAQAh1QEBAOIBACHWAQEA4gEAIREJAACLAgAgCgAAiwIAIBAAAJgCACARAACZAgAgmgEAAJUCADCbAQAADQAQnAEAAJUCADCdAQEA4gEAIaEBQADjAQAh1AEBAOIBACHVAQEA4gEAIdgBAQDiAQAh2QEBAPYBACHaAUAAlgIAIdwBAACXAtwBIt0BAAANACDeAQAADQAgDwkAAIsCACAKAACLAgAgEAAAmAIAIBEAAJkCACCaAQAAlQIAMJsBAAANABCcAQAAlQIAMJ0BAQDiAQAhoQFAAOMBACHUAQEA4gEAIdUBAQDiAQAh2AEBAOIBACHZAQEA9gEAIdoBQACWAgAh3AEAAJcC3AEiCKMBQAAAAAGkAUAAAAAFpQFAAAAABaYBQAAAAAGnAUAAAAABqAFAAAAAAakBQAAAAAGqAUAA6QEAIQSjAQAAANwBAqQBAAAA3AEIpQEAAADcAQiqAQAAkgLcASIKDwAA-wEAIJoBAACOAgAwmwEAADcAEJwBAACOAgAwnQEBAOIBACGhAUAA4wEAIcQBAQDiAQAh1wEBAPYBACHdAQAANwAg3gEAADcAIA8JAACLAgAgCgAAiwIAIAsAAJQCACCaAQAAkwIAMJsBAAARABCcAQAAkwIAMJ0BAQDiAQAhoQFAAOMBACHKAQIAigIAIdMBAQD2AQAh1AEBAOIBACHVAQEA4gEAIdYBAQDiAQAh3QEAABEAIN4BAAARACARAwAAiwIAIJoBAACaAgAwmwEAAAcAEJwBAACaAgAwnQEBAOIBACGhAUAA4wEAIaIBQADjAQAhrgEBAOIBACGvAQEA4gEAIbABAQDiAQAhsQEBAPYBACGyAQEA9gEAIbMBAQD2AQAhtAFAAJYCACG1AUAAlgIAIbYBAQD2AQAhtwEBAPYBACEMAwAAiwIAIJoBAACbAgAwmwEAAAMAEJwBAACbAgAwnQEBAOIBACGgAUAA4wEAIaEBQADjAQAhogFAAOMBACGwAQEA4gEAIbgBAQDiAQAhuQEBAPYBACG6AQEA9gEAIQAAAAHiAQEAAAABAeIBQAAAAAEAAAAAAeIBAQAAAAEB4gFAAAAAAQUeAAD2AwAgHwAA-QMAIN8BAAD3AwAg4AEAAPgDACDlAQAAewAgAx4AAPYDACDfAQAA9wMAIOUBAAB7ACAAAAAFHgAA8QMAIB8AAPQDACDfAQAA8gMAIOABAADzAwAg5QEAAHsAIAMeAADxAwAg3wEAAPIDACDlAQAAewAgAAAAAeIBIAAAAAEB4gEAAADAAQILHgAAjgMAMB8AAJMDADDfAQAAjwMAMOABAACQAwAw4QEAAJEDACDiAQAAkgMAMOMBAACSAwAw5AEAAJIDADDlAQAAkgMAMOYBAACUAwAw5wEAAJUDADALHgAAggMAMB8AAIcDADDfAQAAgwMAMOABAACEAwAw4QEAAIUDACDiAQAAhgMAMOMBAACGAwAw5AEAAIYDADDlAQAAhgMAMOYBAACIAwAw5wEAAIkDADAHHgAA-QIAIB8AAPwCACDfAQAA-gIAIOABAAD7AgAg4wEAAAsAIOQBAAALACDlAQAAYwAgCx4AAO4CADAfAADyAgAw3wEAAO8CADDgAQAA8AIAMOEBAADxAgAg4gEAANoCADDjAQAA2gIAMOQBAADaAgAw5QEAANoCADDmAQAA8wIAMOcBAADdAgAwCx4AANYCADAfAADbAgAw3wEAANcCADDgAQAA2AIAMOEBAADZAgAg4gEAANoCADDjAQAA2gIAMOQBAADaAgAw5QEAANoCADDmAQAA3AIAMOcBAADdAgAwCx4AAMsCADAfAADPAgAw3wEAAMwCADDgAQAAzQIAMOEBAADOAgAg4gEAAL4CADDjAQAAvgIAMOQBAAC-AgAw5QEAAL4CADDmAQAA0AIAMOcBAADBAgAwCx4AALoCADAfAAC_AgAw3wEAALsCADDgAQAAvAIAMOEBAAC9AgAg4gEAAL4CADDjAQAAvgIAMOQBAAC-AgAw5QEAAL4CADDmAQAAwAIAMOcBAADBAgAwCAkAAMkCACALAADKAgAgnQEBAAAAAaEBQAAAAAHKAQIAAAAB0wEBAAAAAdQBAQAAAAHWAQEAAAABAgAAABMAIB4AAMgCACADAAAAEwAgHgAAyAIAIB8AAMUCACABFwAA8AMAMA0JAACLAgAgCgAAiwIAIAsAAJQCACCaAQAAkwIAMJsBAAARABCcAQAAkwIAMJ0BAQAAAAGhAUAA4wEAIcoBAgCKAgAh0wEBAPYBACHUAQEA4gEAIdUBAQDiAQAh1gEBAAAAAQIAAAATACAXAADFAgAgAgAAAMICACAXAADDAgAgCpoBAADBAgAwmwEAAMICABCcAQAAwQIAMJ0BAQDiAQAhoQFAAOMBACHKAQIAigIAIdMBAQD2AQAh1AEBAOIBACHVAQEA4gEAIdYBAQDiAQAhCpoBAADBAgAwmwEAAMICABCcAQAAwQIAMJ0BAQDiAQAhoQFAAOMBACHKAQIAigIAIdMBAQD2AQAh1AEBAOIBACHVAQEA4gEAIdYBAQDiAQAhBp0BAQCfAgAhoQFAAKACACHKAQIAxAIAIdMBAQClAgAh1AEBAJ8CACHWAQEAnwIAIQXiAQIAAAAB6QECAAAAAeoBAgAAAAHrAQIAAAAB7AECAAAAAQgJAADGAgAgCwAAxwIAIJ0BAQCfAgAhoQFAAKACACHKAQIAxAIAIdMBAQClAgAh1AEBAJ8CACHWAQEAnwIAIQUeAADoAwAgHwAA7gMAIN8BAADpAwAg4AEAAO0DACDlAQAAewAgBR4AAOYDACAfAADrAwAg3wEAAOcDACDgAQAA6gMAIOUBAAABACAICQAAyQIAIAsAAMoCACCdAQEAAAABoQFAAAAAAcoBAgAAAAHTAQEAAAAB1AEBAAAAAdYBAQAAAAEDHgAA6AMAIN8BAADpAwAg5QEAAHsAIAMeAADmAwAg3wEAAOcDACDlAQAAAQAgCAoAANUCACALAADKAgAgnQEBAAAAAaEBQAAAAAHKAQIAAAAB0wEBAAAAAdUBAQAAAAHWAQEAAAABAgAAABMAIB4AANQCACADAAAAEwAgHgAA1AIAIB8AANICACABFwAA5QMAMAIAAAATACAXAADSAgAgAgAAAMICACAXAADRAgAgBp0BAQCfAgAhoQFAAKACACHKAQIAxAIAIdMBAQClAgAh1QEBAJ8CACHWAQEAnwIAIQgKAADTAgAgCwAAxwIAIJ0BAQCfAgAhoQFAAKACACHKAQIAxAIAIdMBAQClAgAh1QEBAJ8CACHWAQEAnwIAIQUeAADgAwAgHwAA4wMAIN8BAADhAwAg4AEAAOIDACDlAQAAewAgCAoAANUCACALAADKAgAgnQEBAAAAAaEBQAAAAAHKAQIAAAAB0wEBAAAAAdUBAQAAAAHWAQEAAAABAx4AAOADACDfAQAA4QMAIOUBAAB7ACAKCQAA6wIAIBAAAOwCACARAADtAgAgnQEBAAAAAaEBQAAAAAHUAQEAAAAB2AEBAAAAAdkBAQAAAAHaAUAAAAAB3AEAAADcAQICAAAAAQAgHgAA6gIAIAMAAAABACAeAADqAgAgHwAA4QIAIAEXAADfAwAwDwkAAIsCACAKAACLAgAgEAAAmAIAIBEAAJkCACCaAQAAlQIAMJsBAAANABCcAQAAlQIAMJ0BAQAAAAGhAUAA4wEAIdQBAQDiAQAh1QEBAOIBACHYAQEA4gEAIdkBAQD2AQAh2gFAAJYCACHcAQAAlwLcASICAAAAAQAgFwAA4QIAIAIAAADeAgAgFwAA3wIAIAuaAQAA3QIAMJsBAADeAgAQnAEAAN0CADCdAQEA4gEAIaEBQADjAQAh1AEBAOIBACHVAQEA4gEAIdgBAQDiAQAh2QEBAPYBACHaAUAAlgIAIdwBAACXAtwBIguaAQAA3QIAMJsBAADeAgAQnAEAAN0CADCdAQEA4gEAIaEBQADjAQAh1AEBAOIBACHVAQEA4gEAIdgBAQDiAQAh2QEBAPYBACHaAUAAlgIAIdwBAACXAtwBIgedAQEAnwIAIaEBQACgAgAh1AEBAJ8CACHYAQEAnwIAIdkBAQClAgAh2gFAAKYCACHcAQAA4ALcASIB4gEAAADcAQIKCQAA4gIAIBAAAOMCACARAADkAgAgnQEBAJ8CACGhAUAAoAIAIdQBAQCfAgAh2AEBAJ8CACHZAQEApQIAIdoBQACmAgAh3AEAAOAC3AEiBR4AANcDACAfAADdAwAg3wEAANgDACDgAQAA3AMAIOUBAAB7ACAFHgAA1QMAIB8AANoDACDfAQAA1gMAIOABAADZAwAg5QEAADQAIAceAADlAgAgHwAA6AIAIN8BAADmAgAg4AEAAOcCACDjAQAAEQAg5AEAABEAIOUBAAATACAICQAAyQIAIAoAANUCACCdAQEAAAABoQFAAAAAAcoBAgAAAAHTAQEAAAAB1AEBAAAAAdUBAQAAAAECAAAAEwAgHgAA5QIAIAMAAAARACAeAADlAgAgHwAA6QIAIAoAAAARACAJAADGAgAgCgAA0wIAIBcAAOkCACCdAQEAnwIAIaEBQACgAgAhygECAMQCACHTAQEApQIAIdQBAQCfAgAh1QEBAJ8CACEICQAAxgIAIAoAANMCACCdAQEAnwIAIaEBQACgAgAhygECAMQCACHTAQEApQIAIdQBAQCfAgAh1QEBAJ8CACEKCQAA6wIAIBAAAOwCACARAADtAgAgnQEBAAAAAaEBQAAAAAHUAQEAAAAB2AEBAAAAAdkBAQAAAAHaAUAAAAAB3AEAAADcAQIDHgAA1wMAIN8BAADYAwAg5QEAAHsAIAMeAADVAwAg3wEAANYDACDlAQAANAAgAx4AAOUCACDfAQAA5gIAIOUBAAATACAKCgAA-AIAIBAAAOwCACARAADtAgAgnQEBAAAAAaEBQAAAAAHVAQEAAAAB2AEBAAAAAdkBAQAAAAHaAUAAAAAB3AEAAADcAQICAAAAAQAgHgAA9wIAIAMAAAABACAeAAD3AgAgHwAA9QIAIAEXAADUAwAwAgAAAAEAIBcAAPUCACACAAAA3gIAIBcAAPQCACAHnQEBAJ8CACGhAUAAoAIAIdUBAQCfAgAh2AEBAJ8CACHZAQEApQIAIdoBQACmAgAh3AEAAOAC3AEiCgoAAPYCACAQAADjAgAgEQAA5AIAIJ0BAQCfAgAhoQFAAKACACHVAQEAnwIAIdgBAQCfAgAh2QEBAKUCACHaAUAApgIAIdwBAADgAtwBIgUeAADPAwAgHwAA0gMAIN8BAADQAwAg4AEAANEDACDlAQAAewAgCgoAAPgCACAQAADsAgAgEQAA7QIAIJ0BAQAAAAGhAUAAAAAB1QEBAAAAAdgBAQAAAAHZAQEAAAAB2gFAAAAAAdwBAAAA3AECAx4AAM8DACDfAQAA0AMAIOUBAAB7ACAOnQEBAAAAAaEBQAAAAAHEAQEAAAABxQEBAAAAAcYBAQAAAAHHAQIAAAAByAECAAAAAckBAQAAAAHKAQgAAAABywECAAAAAcwBAgAAAAHNAQIAAAABzgEAAIEDACDPASAAAAABAgAAAGMAIB4AAPkCACADAAAACwAgHgAA-QIAIB8AAP0CACAQAAAACwAgFwAA_QIAIJ0BAQCfAgAhoQFAAKACACHEAQEApQIAIcUBAQClAgAhxgEBAKUCACHHAQIA_gIAIcgBAgD-AgAhyQEBAKUCACHKAQgA_wIAIcsBAgDEAgAhzAECAMQCACHNAQIAxAIAIc4BAACAAwAgzwEgALECACEOnQEBAJ8CACGhAUAAoAIAIcQBAQClAgAhxQEBAKUCACHGAQEApQIAIccBAgD-AgAhyAECAP4CACHJAQEApQIAIcoBCAD_AgAhywECAMQCACHMAQIAxAIAIc0BAgDEAgAhzgEAAIADACDPASAAsQIAIQXiAQIAAAAB6QECAAAAAeoBAgAAAAHrAQIAAAAB7AECAAAAAQXiAQgAAAAB6QEIAAAAAeoBCAAAAAHrAQgAAAAB7AEIAAAAAQLiAQEAAAAE6AEBAAAABQHiAQEAAAAEDJ0BAQAAAAGhAUAAAAABogFAAAAAAa4BAQAAAAGvAQEAAAABsQEBAAAAAbIBAQAAAAGzAQEAAAABtAFAAAAAAbUBQAAAAAG2AQEAAAABtwEBAAAAAQIAAAAJACAeAACNAwAgAwAAAAkAIB4AAI0DACAfAACMAwAgARcAAM4DADARAwAAiwIAIJoBAACaAgAwmwEAAAcAEJwBAACaAgAwnQEBAAAAAaEBQADjAQAhogFAAOMBACGuAQEA4gEAIa8BAQDiAQAhsAEBAOIBACGxAQEA9gEAIbIBAQD2AQAhswEBAPYBACG0AUAAlgIAIbUBQACWAgAhtgEBAPYBACG3AQEA9gEAIQIAAAAJACAXAACMAwAgAgAAAIoDACAXAACLAwAgEJoBAACJAwAwmwEAAIoDABCcAQAAiQMAMJ0BAQDiAQAhoQFAAOMBACGiAUAA4wEAIa4BAQDiAQAhrwEBAOIBACGwAQEA4gEAIbEBAQD2AQAhsgEBAPYBACGzAQEA9gEAIbQBQACWAgAhtQFAAJYCACG2AQEA9gEAIbcBAQD2AQAhEJoBAACJAwAwmwEAAIoDABCcAQAAiQMAMJ0BAQDiAQAhoQFAAOMBACGiAUAA4wEAIa4BAQDiAQAhrwEBAOIBACGwAQEA4gEAIbEBAQD2AQAhsgEBAPYBACGzAQEA9gEAIbQBQACWAgAhtQFAAJYCACG2AQEA9gEAIbcBAQD2AQAhDJ0BAQCfAgAhoQFAAKACACGiAUAAoAIAIa4BAQCfAgAhrwEBAJ8CACGxAQEApQIAIbIBAQClAgAhswEBAKUCACG0AUAApgIAIbUBQACmAgAhtgEBAKUCACG3AQEApQIAIQydAQEAnwIAIaEBQACgAgAhogFAAKACACGuAQEAnwIAIa8BAQCfAgAhsQEBAKUCACGyAQEApQIAIbMBAQClAgAhtAFAAKYCACG1AUAApgIAIbYBAQClAgAhtwEBAKUCACEMnQEBAAAAAaEBQAAAAAGiAUAAAAABrgEBAAAAAa8BAQAAAAGxAQEAAAABsgEBAAAAAbMBAQAAAAG0AUAAAAABtQFAAAAAAbYBAQAAAAG3AQEAAAABB50BAQAAAAGgAUAAAAABoQFAAAAAAaIBQAAAAAG4AQEAAAABuQEBAAAAAboBAQAAAAECAAAABQAgHgAAmQMAIAMAAAAFACAeAACZAwAgHwAAmAMAIAEXAADNAwAwDAMAAIsCACCaAQAAmwIAMJsBAAADABCcAQAAmwIAMJ0BAQAAAAGgAUAA4wEAIaEBQADjAQAhogFAAOMBACGwAQEA4gEAIbgBAQAAAAG5AQEA9gEAIboBAQD2AQAhAgAAAAUAIBcAAJgDACACAAAAlgMAIBcAAJcDACALmgEAAJUDADCbAQAAlgMAEJwBAACVAwAwnQEBAOIBACGgAUAA4wEAIaEBQADjAQAhogFAAOMBACGwAQEA4gEAIbgBAQDiAQAhuQEBAPYBACG6AQEA9gEAIQuaAQAAlQMAMJsBAACWAwAQnAEAAJUDADCdAQEA4gEAIaABQADjAQAhoQFAAOMBACGiAUAA4wEAIbABAQDiAQAhuAEBAOIBACG5AQEA9gEAIboBAQD2AQAhB50BAQCfAgAhoAFAAKACACGhAUAAoAIAIaIBQACgAgAhuAEBAJ8CACG5AQEApQIAIboBAQClAgAhB50BAQCfAgAhoAFAAKACACGhAUAAoAIAIaIBQACgAgAhuAEBAJ8CACG5AQEApQIAIboBAQClAgAhB50BAQAAAAGgAUAAAAABoQFAAAAAAaIBQAAAAAG4AQEAAAABuQEBAAAAAboBAQAAAAEEHgAAjgMAMN8BAACPAwAw4QEAAJEDACDlAQAAkgMAMAQeAACCAwAw3wEAAIMDADDhAQAAhQMAIOUBAACGAwAwAx4AAPkCACDfAQAA-gIAIOUBAABjACAEHgAA7gIAMN8BAADvAgAw4QEAAPECACDlAQAA2gIAMAQeAADWAgAw3wEAANcCADDhAQAA2QIAIOUBAADaAgAwBB4AAMsCADDfAQAAzAIAMOEBAADOAgAg5QEAAL4CADAEHgAAugIAMN8BAAC7AgAw4QEAAL0CACDlAQAAvgIAMAAABwMAAK0DACDEAQAAoQIAIMUBAAChAgAgxgEAAKECACDHAQAAoQIAIMgBAAChAgAgyQEAAKECACAAAAAAAAAABR4AAMgDACAfAADLAwAg3wEAAMkDACDgAQAAygMAIOUBAAB7ACADHgAAyAMAIN8BAADJAwAg5QEAAHsAIAgEAAChAwAgBQAAogMAIAYAAKMDACAHAACkAwAgCAAApAMAIAwAAKUDACANAAClAwAgvgEAAKECACAAAAAAAAAAAAseAAC3AwAwHwAAuwMAMN8BAAC4AwAw4AEAALkDADDhAQAAugMAIOIBAADaAgAw4wEAANoCADDkAQAA2gIAMOUBAADaAgAw5gEAALwDADDnAQAA3QIAMAoJAADrAgAgCgAA-AIAIBEAAO0CACCdAQEAAAABoQFAAAAAAdQBAQAAAAHVAQEAAAAB2QEBAAAAAdoBQAAAAAHcAQAAANwBAgIAAAABACAeAAC_AwAgAwAAAAEAIB4AAL8DACAfAAC-AwAgARcAAMcDADACAAAAAQAgFwAAvgMAIAIAAADeAgAgFwAAvQMAIAedAQEAnwIAIaEBQACgAgAh1AEBAJ8CACHVAQEAnwIAIdkBAQClAgAh2gFAAKYCACHcAQAA4ALcASIKCQAA4gIAIAoAAPYCACARAADkAgAgnQEBAJ8CACGhAUAAoAIAIdQBAQCfAgAh1QEBAJ8CACHZAQEApQIAIdoBQACmAgAh3AEAAOAC3AEiCgkAAOsCACAKAAD4AgAgEQAA7QIAIJ0BAQAAAAGhAUAAAAAB1AEBAAAAAdUBAQAAAAHZAQEAAAAB2gFAAAAAAdwBAAAA3AECBB4AALcDADDfAQAAuAMAMOEBAAC6AwAg5QEAANoCADAAAAAGCQAArQMAIAoAAK0DACAQAADFAwAgEQAAxgMAINkBAAChAgAg2gEAAKECACACDwAApAMAINcBAAChAgAgBAkAAK0DACAKAACtAwAgCwAAxAMAINMBAAChAgAgB50BAQAAAAGhAUAAAAAB1AEBAAAAAdUBAQAAAAHZAQEAAAAB2gFAAAAAAdwBAAAA3AECDgQAAJoDACAFAACbAwAgBwAAnQMAIAgAAJ4DACAMAACfAwAgDQAAoAMAIJ0BAQAAAAGhAUAAAAABogFAAAAAAbsBAQAAAAG8AQEAAAABvQEgAAAAAb4BAQAAAAHAAQAAAMABAgIAAAB7ACAeAADIAwAgAwAAAH4AIB4AAMgDACAfAADMAwAgEAAAAH4AIAQAALMCACAFAAC0AgAgBwAAtgIAIAgAALcCACAMAAC4AgAgDQAAuQIAIBcAAMwDACCdAQEAnwIAIaEBQACgAgAhogFAAKACACG7AQEAnwIAIbwBAQCfAgAhvQEgALECACG-AQEApQIAIcABAACyAsABIg4EAACzAgAgBQAAtAIAIAcAALYCACAIAAC3AgAgDAAAuAIAIA0AALkCACCdAQEAnwIAIaEBQACgAgAhogFAAKACACG7AQEAnwIAIbwBAQCfAgAhvQEgALECACG-AQEApQIAIcABAACyAsABIgedAQEAAAABoAFAAAAAAaEBQAAAAAGiAUAAAAABuAEBAAAAAbkBAQAAAAG6AQEAAAABDJ0BAQAAAAGhAUAAAAABogFAAAAAAa4BAQAAAAGvAQEAAAABsQEBAAAAAbIBAQAAAAGzAQEAAAABtAFAAAAAAbUBQAAAAAG2AQEAAAABtwEBAAAAAQ4EAACaAwAgBQAAmwMAIAYAAJwDACAHAACdAwAgDAAAnwMAIA0AAKADACCdAQEAAAABoQFAAAAAAaIBQAAAAAG7AQEAAAABvAEBAAAAAb0BIAAAAAG-AQEAAAABwAEAAADAAQICAAAAewAgHgAAzwMAIAMAAAB-ACAeAADPAwAgHwAA0wMAIBAAAAB-ACAEAACzAgAgBQAAtAIAIAYAALUCACAHAAC2AgAgDAAAuAIAIA0AALkCACAXAADTAwAgnQEBAJ8CACGhAUAAoAIAIaIBQACgAgAhuwEBAJ8CACG8AQEAnwIAIb0BIACxAgAhvgEBAKUCACHAAQAAsgLAASIOBAAAswIAIAUAALQCACAGAAC1AgAgBwAAtgIAIAwAALgCACANAAC5AgAgnQEBAJ8CACGhAUAAoAIAIaIBQACgAgAhuwEBAJ8CACG8AQEAnwIAIb0BIACxAgAhvgEBAKUCACHAAQAAsgLAASIHnQEBAAAAAaEBQAAAAAHVAQEAAAAB2AEBAAAAAdkBAQAAAAHaAUAAAAAB3AEAAADcAQIEnQEBAAAAAaEBQAAAAAHEAQEAAAAB1wEBAAAAAQIAAAA0ACAeAADVAwAgDgQAAJoDACAFAACbAwAgBgAAnAMAIAgAAJ4DACAMAACfAwAgDQAAoAMAIJ0BAQAAAAGhAUAAAAABogFAAAAAAbsBAQAAAAG8AQEAAAABvQEgAAAAAb4BAQAAAAHAAQAAAMABAgIAAAB7ACAeAADXAwAgAwAAADcAIB4AANUDACAfAADbAwAgBgAAADcAIBcAANsDACCdAQEAnwIAIaEBQACgAgAhxAEBAJ8CACHXAQEApQIAIQSdAQEAnwIAIaEBQACgAgAhxAEBAJ8CACHXAQEApQIAIQMAAAB-ACAeAADXAwAgHwAA3gMAIBAAAAB-ACAEAACzAgAgBQAAtAIAIAYAALUCACAIAAC3AgAgDAAAuAIAIA0AALkCACAXAADeAwAgnQEBAJ8CACGhAUAAoAIAIaIBQACgAgAhuwEBAJ8CACG8AQEAnwIAIb0BIACxAgAhvgEBAKUCACHAAQAAsgLAASIOBAAAswIAIAUAALQCACAGAAC1AgAgCAAAtwIAIAwAALgCACANAAC5AgAgnQEBAJ8CACGhAUAAoAIAIaIBQACgAgAhuwEBAJ8CACG8AQEAnwIAIb0BIACxAgAhvgEBAKUCACHAAQAAsgLAASIHnQEBAAAAAaEBQAAAAAHUAQEAAAAB2AEBAAAAAdkBAQAAAAHaAUAAAAAB3AEAAADcAQIOBAAAmgMAIAUAAJsDACAGAACcAwAgBwAAnQMAIAgAAJ4DACAMAACfAwAgnQEBAAAAAaEBQAAAAAGiAUAAAAABuwEBAAAAAbwBAQAAAAG9ASAAAAABvgEBAAAAAcABAAAAwAECAgAAAHsAIB4AAOADACADAAAAfgAgHgAA4AMAIB8AAOQDACAQAAAAfgAgBAAAswIAIAUAALQCACAGAAC1AgAgBwAAtgIAIAgAALcCACAMAAC4AgAgFwAA5AMAIJ0BAQCfAgAhoQFAAKACACGiAUAAoAIAIbsBAQCfAgAhvAEBAJ8CACG9ASAAsQIAIb4BAQClAgAhwAEAALICwAEiDgQAALMCACAFAAC0AgAgBgAAtQIAIAcAALYCACAIAAC3AgAgDAAAuAIAIJ0BAQCfAgAhoQFAAKACACGiAUAAoAIAIbsBAQCfAgAhvAEBAJ8CACG9ASAAsQIAIb4BAQClAgAhwAEAALICwAEiBp0BAQAAAAGhAUAAAAABygECAAAAAdMBAQAAAAHVAQEAAAAB1gEBAAAAAQsJAADrAgAgCgAA-AIAIBAAAOwCACCdAQEAAAABoQFAAAAAAdQBAQAAAAHVAQEAAAAB2AEBAAAAAdkBAQAAAAHaAUAAAAAB3AEAAADcAQICAAAAAQAgHgAA5gMAIA4EAACaAwAgBQAAmwMAIAYAAJwDACAHAACdAwAgCAAAngMAIA0AAKADACCdAQEAAAABoQFAAAAAAaIBQAAAAAG7AQEAAAABvAEBAAAAAb0BIAAAAAG-AQEAAAABwAEAAADAAQICAAAAewAgHgAA6AMAIAMAAAANACAeAADmAwAgHwAA7AMAIA0AAAANACAJAADiAgAgCgAA9gIAIBAAAOMCACAXAADsAwAgnQEBAJ8CACGhAUAAoAIAIdQBAQCfAgAh1QEBAJ8CACHYAQEAnwIAIdkBAQClAgAh2gFAAKYCACHcAQAA4ALcASILCQAA4gIAIAoAAPYCACAQAADjAgAgnQEBAJ8CACGhAUAAoAIAIdQBAQCfAgAh1QEBAJ8CACHYAQEAnwIAIdkBAQClAgAh2gFAAKYCACHcAQAA4ALcASIDAAAAfgAgHgAA6AMAIB8AAO8DACAQAAAAfgAgBAAAswIAIAUAALQCACAGAAC1AgAgBwAAtgIAIAgAALcCACANAAC5AgAgFwAA7wMAIJ0BAQCfAgAhoQFAAKACACGiAUAAoAIAIbsBAQCfAgAhvAEBAJ8CACG9ASAAsQIAIb4BAQClAgAhwAEAALICwAEiDgQAALMCACAFAAC0AgAgBgAAtQIAIAcAALYCACAIAAC3AgAgDQAAuQIAIJ0BAQCfAgAhoQFAAKACACGiAUAAoAIAIbsBAQCfAgAhvAEBAJ8CACG9ASAAsQIAIb4BAQClAgAhwAEAALICwAEiBp0BAQAAAAGhAUAAAAABygECAAAAAdMBAQAAAAHUAQEAAAAB1gEBAAAAAQ4FAACbAwAgBgAAnAMAIAcAAJ0DACAIAACeAwAgDAAAnwMAIA0AAKADACCdAQEAAAABoQFAAAAAAaIBQAAAAAG7AQEAAAABvAEBAAAAAb0BIAAAAAG-AQEAAAABwAEAAADAAQICAAAAewAgHgAA8QMAIAMAAAB-ACAeAADxAwAgHwAA9QMAIBAAAAB-ACAFAAC0AgAgBgAAtQIAIAcAALYCACAIAAC3AgAgDAAAuAIAIA0AALkCACAXAAD1AwAgnQEBAJ8CACGhAUAAoAIAIaIBQACgAgAhuwEBAJ8CACG8AQEAnwIAIb0BIACxAgAhvgEBAKUCACHAAQAAsgLAASIOBQAAtAIAIAYAALUCACAHAAC2AgAgCAAAtwIAIAwAALgCACANAAC5AgAgnQEBAJ8CACGhAUAAoAIAIaIBQACgAgAhuwEBAJ8CACG8AQEAnwIAIb0BIACxAgAhvgEBAKUCACHAAQAAsgLAASIOBAAAmgMAIAYAAJwDACAHAACdAwAgCAAAngMAIAwAAJ8DACANAACgAwAgnQEBAAAAAaEBQAAAAAGiAUAAAAABuwEBAAAAAbwBAQAAAAG9ASAAAAABvgEBAAAAAcABAAAAwAECAgAAAHsAIB4AAPYDACADAAAAfgAgHgAA9gMAIB8AAPoDACAQAAAAfgAgBAAAswIAIAYAALUCACAHAAC2AgAgCAAAtwIAIAwAALgCACANAAC5AgAgFwAA-gMAIJ0BAQCfAgAhoQFAAKACACGiAUAAoAIAIbsBAQCfAgAhvAEBAJ8CACG9ASAAsQIAIb4BAQClAgAhwAEAALICwAEiDgQAALMCACAGAAC1AgAgBwAAtgIAIAgAALcCACAMAAC4AgAgDQAAuQIAIJ0BAQCfAgAhoQFAAKACACGiAUAAoAIAIbsBAQCfAgAhvAEBAJ8CACG9ASAAsQIAIb4BAQClAgAhwAEAALICwAEiBAkAAgoAAhAACBEeBggEBgMFCgQGDAUHDwEIEAEMFAYNFQYOAAcBAwACAQMAAgEDAAIDCQACCgACCwABBgQWAAUXAAcYAAgZAAwaAA0bAAIOAAkPHAEBDx0AAAMJAAIKAAIQAAgDCQACCgACEAAIAw4ADiQADyUAEAAAAAMOAA4kAA8lABAAAAMOABUkABYlABcAAAADDgAVJAAWJQAXAwkAAgoAAgsAAQMJAAIKAAILAAEFDgAcJAAfJQAgRgAdRwAeAAAAAAAFDgAcJAAfJQAgRgAdRwAeAQMAAgEDAAIFDgAlJAAoJQApRgAmRwAnAAAAAAAFDgAlJAAoJQApRgAmRwAnAAADDgAuJAAvJQAwAAAAAw4ALiQALyUAMAEDAAIBAwACAw4ANSQANiUANwAAAAMOADUkADYlADcBAwACAQMAAgMOADwkAD0lAD4AAAADDgA8JAA9JQA-AAAAAw4ARCQARSUARgAAAAMOAEQkAEUlAEYSAgETHwEUIAEVIQEWIgEYJAEZJgoaJwsbKQEcKwodLAwgLQEhLgEiLwomMg0nMxEoNQgpNggqOQgrOggsOwgtPQguPwovQBIwQggxRAoyRRMzRgg0Rwg1SAo2SxQ3TBg4TQY5TgY6TwY7UAY8UQY9UwY-VQo_VhlAWAZBWgpCWxpDXAZEXQZFXgpIYRtJYiFKZAVLZQVMZwVNaAVOaQVPawVQbQpRbiJScAVTcgpUcyNVdAVWdQVXdgpYeSRZeipafAJbfQJcgAECXYEBAl6CAQJfhAECYIYBCmGHAStiiQECY4sBCmSMASxljQECZo4BAmePAQpokgEtaZMBMWqUAQNrlQEDbJYBA22XAQNumAEDb5oBA3CcAQpxnQEycp8BA3OhAQp0ogEzdaMBA3akAQN3pQEKeKgBNHmpATh6qgEEe6sBBHysAQR9rQEEfq4BBH-wAQSAAbIBCoEBswE5ggG1AQSDAbcBCoQBuAE6hQG5AQSGAboBBIcBuwEKiAG-ATuJAb8BP4oBwQFAiwHCAUCMAcUBQI0BxgFAjgHHAUCPAckBQJABywEKkQHMAUGSAc4BQJMB0AEKlAHRAUKVAdIBQJYB0wFAlwHUAQqYAdcBQ5kB2AFH"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer: Buffer2 } = await import("buffer");
  const wasmArray = Buffer2.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
var prismaNamespace_exports = {};
__export(prismaNamespace_exports, {
  AccountScalarFieldEnum: () => AccountScalarFieldEnum,
  AnyNull: () => AnyNull2,
  BookingScalarFieldEnum: () => BookingScalarFieldEnum,
  CategoryScalarFieldEnum: () => CategoryScalarFieldEnum,
  DbNull: () => DbNull2,
  Decimal: () => Decimal2,
  JsonNull: () => JsonNull2,
  ModelName: () => ModelName,
  NullTypes: () => NullTypes2,
  NullsOrder: () => NullsOrder,
  PrismaClientInitializationError: () => PrismaClientInitializationError2,
  PrismaClientKnownRequestError: () => PrismaClientKnownRequestError2,
  PrismaClientRustPanicError: () => PrismaClientRustPanicError2,
  PrismaClientUnknownRequestError: () => PrismaClientUnknownRequestError2,
  PrismaClientValidationError: () => PrismaClientValidationError2,
  QueryMode: () => QueryMode,
  ReviewScalarFieldEnum: () => ReviewScalarFieldEnum,
  SessionScalarFieldEnum: () => SessionScalarFieldEnum,
  SortOrder: () => SortOrder,
  Sql: () => Sql2,
  TransactionIsolationLevel: () => TransactionIsolationLevel,
  TutorProfileScalarFieldEnum: () => TutorProfileScalarFieldEnum,
  UserScalarFieldEnum: () => UserScalarFieldEnum,
  VerificationScalarFieldEnum: () => VerificationScalarFieldEnum,
  defineExtension: () => defineExtension,
  empty: () => empty2,
  getExtensionContext: () => getExtensionContext,
  join: () => join2,
  prismaVersion: () => prismaVersion,
  raw: () => raw2,
  sql: () => sql
});
import * as runtime2 from "@prisma/client/runtime/client";
var PrismaClientKnownRequestError2 = runtime2.PrismaClientKnownRequestError;
var PrismaClientUnknownRequestError2 = runtime2.PrismaClientUnknownRequestError;
var PrismaClientRustPanicError2 = runtime2.PrismaClientRustPanicError;
var PrismaClientInitializationError2 = runtime2.PrismaClientInitializationError;
var PrismaClientValidationError2 = runtime2.PrismaClientValidationError;
var sql = runtime2.sqltag;
var empty2 = runtime2.empty;
var join2 = runtime2.join;
var raw2 = runtime2.raw;
var Sql2 = runtime2.Sql;
var Decimal2 = runtime2.Decimal;
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var prismaVersion = {
  client: "7.4.1",
  engine: "55ae170b1ced7fc6ed07a15f110549408c501bb3"
};
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var DbNull2 = runtime2.DbNull;
var JsonNull2 = runtime2.JsonNull;
var AnyNull2 = runtime2.AnyNull;
var ModelName = {
  Booking: "Booking",
  Category: "Category",
  Review: "Review",
  TutorProfile: "TutorProfile",
  User: "User",
  Session: "Session",
  Account: "Account",
  Verification: "Verification"
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var BookingScalarFieldEnum = {
  id: "id",
  studentId: "studentId",
  tutorId: "tutorId",
  categoryId: "categoryId",
  message: "message",
  date: "date",
  status: "status",
  createdAt: "createdAt"
};
var CategoryScalarFieldEnum = {
  id: "id",
  title: "title",
  description: "description",
  createdAt: "createdAt"
};
var ReviewScalarFieldEnum = {
  id: "id",
  rating: "rating",
  comment: "comment",
  studentId: "studentId",
  tutorId: "tutorId",
  bookingId: "bookingId",
  createdAt: "createdAt"
};
var TutorProfileScalarFieldEnum = {
  id: "id",
  userId: "userId",
  title: "title",
  bio: "bio",
  education: "education",
  experienceYears: "experienceYears",
  hourlyRate: "hourlyRate",
  availability: "availability",
  rating: "rating",
  totalReviews: "totalReviews",
  totalStudents: "totalStudents",
  completedSessions: "completedSessions",
  languages: "languages",
  verified: "verified",
  createdAt: "createdAt"
};
var UserScalarFieldEnum = {
  id: "id",
  name: "name",
  email: "email",
  emailVerified: "emailVerified",
  image: "image",
  role: "role",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var SessionScalarFieldEnum = {
  id: "id",
  expiresAt: "expiresAt",
  token: "token",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  ipAddress: "ipAddress",
  userAgent: "userAgent",
  userId: "userId"
};
var AccountScalarFieldEnum = {
  id: "id",
  accountId: "accountId",
  providerId: "providerId",
  userId: "userId",
  accessToken: "accessToken",
  refreshToken: "refreshToken",
  idToken: "idToken",
  accessTokenExpiresAt: "accessTokenExpiresAt",
  refreshTokenExpiresAt: "refreshTokenExpiresAt",
  scope: "scope",
  password: "password",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var VerificationScalarFieldEnum = {
  id: "id",
  identifier: "identifier",
  value: "value",
  expiresAt: "expiresAt",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var SortOrder = {
  asc: "asc",
  desc: "desc"
};
var QueryMode = {
  default: "default",
  insensitive: "insensitive"
};
var NullsOrder = {
  first: "first",
  last: "last"
};
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
var connectionString = `${process.env.DATABASE_URL}`;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/modules/tutorProfile/tutorProfile.service.ts
var createTutorProfile = async (userId, payload) => {
  const existing = await prisma.tutorProfile.findUnique({
    where: { userId }
  });
  if (existing) {
    throw new Error("Tutor profile already exists");
  }
  const result = await prisma.tutorProfile.create({
    data: {
      userId,
      ...payload
    }
  });
  return result;
};
var getAllTutors = async () => {
  return prisma.tutorProfile.findMany({
    include: {
      user: true
    }
  });
};
var getSingleTutor = async (id) => {
  return prisma.tutorProfile.findUnique({
    where: { id },
    include: {
      user: true
    }
  });
};
var updateTutorProfile = async (userId, payload) => {
  return prisma.tutorProfile.update({
    where: { userId },
    data: payload
  });
};
var updateAvailability = async (userId, availability) => {
  return prisma.tutorProfile.update({
    where: { userId },
    data: { availability }
  });
};
var TutorProfileService = {
  createTutorProfile,
  getAllTutors,
  getSingleTutor,
  updateTutorProfile,
  updateAvailability
};

// src/utils/catchAsync.ts
var catchAsync = (fn) => {
  return (req, res, next) => {
    fn(req, res, next).catch(next);
  };
};
var catchAsync_default = catchAsync;

// src/modules/tutorProfile/tutorProfile.controller.ts
var createTutorProfile2 = catchAsync_default(async (req, res) => {
  const user = req.user;
  if (!user) {
    return res.status(401).json({
      success: false,
      message: "Unauthorized"
    });
  }
  const result = await TutorProfileService.createTutorProfile(
    user.id,
    req.body
  );
  res.status(201).json({
    success: true,
    message: "Tutor profile created successfully",
    data: result
  });
});
var getAllTutors2 = catchAsync_default(async (req, res) => {
  const result = await TutorProfileService.getAllTutors();
  res.status(200).json({
    success: true,
    data: result
  });
});
var getSingleTutor2 = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const result = await TutorProfileService.getSingleTutor(id);
  res.status(200).json({
    success: true,
    data: result
  });
});
var updateTutorProfile2 = catchAsync_default(async (req, res) => {
  const userId = req.user.id;
  const result = await TutorProfileService.updateTutorProfile(
    userId,
    req.body
  );
  res.status(200).json({
    success: true,
    message: "Tutor profile updated",
    data: result
  });
});
var updateAvailability2 = catchAsync_default(async (req, res) => {
  const userId = req.user.id;
  const result = await TutorProfileService.updateAvailability(
    userId,
    req.body.availability
  );
  res.status(200).json({
    success: true,
    message: "Availability updated",
    data: result
  });
});
var TutorProfileController = {
  createTutorProfile: createTutorProfile2,
  getAllTutors: getAllTutors2,
  getSingleTutor: getSingleTutor2,
  updateTutorProfile: updateTutorProfile2,
  updateAvailability: updateAvailability2
};

// src/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import nodemailer from "nodemailer";
var transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false,
  // Use true for port 465, false for port 587
  auth: {
    user: process.env.APP_USER,
    pass: process.env.APP_PASS
  }
});
var auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: "postgresql"
    // or "mysql", "postgresql", ...etc
  }),
  emailAndPassword: {
    enabled: true,
    autoSignIn: true,
    requireEmailVerification: true
  },
  user: {
    additionalFields: {
      role: {
        type: "string",
        required: false
      }
    }
  },
  trustedOrigins: [process.env.APP_URL, "http://localhost:3000"],
  emailVerification: {
    sendOnSignUp: true,
    autoSignInAfterVerification: true,
    sendVerificationEmail: async ({ user, url, token }, request) => {
      try {
        const verificationUrl = `${process.env.APP_URL}/verify-email?token=${token}`;
        const info = await transporter.sendMail({
          from: `"SkillBridge" <${process.env.APP_USER}>`,
          to: user.email,
          subject: "Verify Your Email - SkillBridge",
          html: `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Verify Your Email - SkillBridge</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      background-color: #fbfbfe;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
    }
    .container {
      max-width: 600px;
      margin: 40px auto;
      background-color: #ffffff;
      border-radius: 12px;
      overflow: hidden;
      box-shadow: 0 4px 20px rgba(47, 39, 206, 0.08);
    }
    .header {
      background: linear-gradient(135deg, #2f27ce 0%, #443dff 100%);
      color: #ffffff;
      padding: 32px 24px;
      text-align: center;
    }
    .header h1 {
      margin: 0;
      font-size: 28px;
      font-weight: 900;
      letter-spacing: -0.5px;
    }
    .content {
      padding: 40px 32px;
      color: #040316;
      line-height: 1.6;
    }
    .content h2 {
      margin-top: 0;
      font-size: 24px;
      font-weight: 700;
      color: #040316;
      margin-bottom: 16px;
    }
    .content p {
      margin: 0 0 16px 0;
      color: #040316;
      opacity: 0.75;
      font-size: 16px;
    }
    .button-wrapper {
      text-align: center;
      margin: 32px 0;
    }
    .verify-button {
      background: linear-gradient(135deg, #2f27ce 0%, #443dff 100%);
      color: #ffffff !important;
      padding: 16px 48px;
      text-decoration: none;
      font-weight: 600;
      font-size: 16px;
      border-radius: 12px;
      display: inline-block;
      box-shadow: 0 4px 12px rgba(47, 39, 206, 0.3);
    }
    .verify-button:hover {
      opacity: 0.9;
    }
    .divider {
      margin: 32px 0;
      border: none;
      border-top: 1px solid #dddbff;
    }
    .link-section {
      background-color: #f5f3ff;
      border: 2px dashed #dddbff;
      border-radius: 12px;
      padding: 16px;
      margin: 24px 0;
    }
    .link-section p {
      margin: 0 0 8px 0;
      font-size: 13px;
      color: #040316;
      opacity: 0.6;
    }
    .link {
      word-break: break-all;
      font-size: 13px;
      color: #2f27ce;
      font-family: 'Courier New', monospace;
    }
    .warning {
      background-color: #fff8ed;
      border-left: 4px solid #ff9500;
      padding: 16px;
      margin: 24px 0;
      border-radius: 8px;
    }
    .warning p {
      margin: 0;
      font-size: 14px;
      color: #040316;
      opacity: 0.7;
    }
    .footer {
      background-color: #fbfbfe;
      padding: 24px 32px;
      text-align: center;
      border-top: 1px solid #dddbff;
    }
    .footer p {
      margin: 4px 0;
      font-size: 13px;
      color: #040316;
      opacity: 0.5;
    }
    .footer-links {
      margin-top: 12px;
    }
    .footer-link {
      color: #2f27ce;
      text-decoration: none;
      font-size: 13px;
      margin: 0 8px;
    }
    @media only screen and (max-width: 600px) {
      .content {
        padding: 30px 20px;
      }
      .content h2 {
        font-size: 20px;
      }
      .verify-button {
        padding: 14px 32px;
        font-size: 15px;
      }
    }
  </style>
</head>
<body>
  <div class="container">
    <!-- Header -->
    <div class="header">
      <h1>SkillBridge</h1>
    </div>

    <!-- Content -->
    <div class="content">
      <h2>Verify Your Email Address</h2>
      <p>
        Hello <strong>${user.name}</strong>,
      </p>
      <p>
        Welcome to <strong>SkillBridge</strong>! We're excited to have you join our community of learners and expert tutors.
      </p>
      <p>
        To complete your registration and start connecting with tutors, please verify your email address by clicking the button below:
      </p>

      <!-- Verify Button -->
      <div class="button-wrapper">
        <a href="${verificationUrl}" class="verify-button">
          Verify Email Address
        </a>
      </div>

      <hr class="divider" />

      <!-- Alternative Link -->
      <div class="link-section">
        <p><strong>Button not working?</strong> Copy and paste this link into your browser:</p>
        <p class="link">${url}</p>
      </div>

      <!-- Warning -->
      <div class="warning">
        <p>
          <strong>\u26A0\uFE0F Security Note:</strong> This verification link will expire soon for security reasons.
          If you did not create an account with SkillBridge, please ignore this email.
        </p>
      </div>

      <p style="margin-top: 32px;">
        Once verified, you'll be able to:
      </p>
      <ul style="margin: 12px 0; padding-left: 20px; color: #040316; opacity: 0.75;">
        <li>Browse thousands of expert tutors</li>
        <li>Book learning sessions instantly</li>
        <li>Track your progress and achievements</li>
      </ul>

      <p style="margin-top: 24px;">
        Best regards,<br />
        <strong>The SkillBridge Team</strong>
      </p>
    </div>

    <!-- Footer -->
    <div class="footer">
      <p>\xA9 ${(/* @__PURE__ */ new Date()).getFullYear()} SkillBridge. All rights reserved.</p>
      <p>Connect with expert tutors and master new skills.</p>
      <div class="footer-links">
        <a href="${process.env.APP_URL}/help" class="footer-link">Help Center</a>
        <a href="${process.env.APP_URL}/privacy" class="footer-link">Privacy</a>
        <a href="${process.env.APP_URL}/terms" class="footer-link">Terms</a>
      </div>
    </div>
  </div>
</body>
</html>
`
        });
        console.log("Verification email sent:", info.messageId);
      } catch (err) {
        console.error("Error sending verification email:", err);
        throw err;
      }
    }
  },
  socialProviders: {
    google: {
      prompt: "select_account consent",
      accessType: "offline",
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET
    },
    github: {
      clientId: process.env.GITHUB_CLIENT_ID,
      clientSecret: process.env.GITHUB_CLIENT_SECRET
    }
  },
  redirects: {
    signInSuccess: process.env.APP_URL
  }
});

// src/middlewares/auth.ts
var auth2 = (...roles) => {
  return async (req, res, next) => {
    try {
      const session = await auth.api.getSession({
        headers: req.headers
      });
      if (!session) {
        return res.status(401).json({
          success: false,
          message: "Unauthorized! Please login first."
        });
      }
      req.user = {
        id: session.user.id,
        email: session.user.email,
        name: session.user.name,
        role: session.user.role,
        emailVerified: session.user.emailVerified
      };
      if (roles.length && !roles.includes(req.user.role)) {
        return res.status(403).json({
          success: false,
          message: "Forbidden! You don't have permission."
        });
      }
      next();
    } catch (error) {
      next(error);
    }
  };
};
var auth_default = auth2;

// src/modules/tutorProfile/tutorProfile.route.ts
var router = express.Router();
router.post(
  "/",
  auth_default("TUTOR" /* TUTOR */),
  TutorProfileController.createTutorProfile
);
router.get("/", TutorProfileController.getAllTutors);
router.get("/:id", TutorProfileController.getSingleTutor);
router.put(
  "/profile",
  auth_default("TUTOR" /* TUTOR */),
  TutorProfileController.updateTutorProfile
);
router.put(
  "/availability",
  auth_default("TUTOR" /* TUTOR */),
  TutorProfileController.updateAvailability
);
var TutorProfileRoutes = router;

// src/app.ts
import { toNodeHandler } from "better-auth/node";

// src/middlewares/errorHandler.ts
var errorHandler = (err, req, res, next) => {
  let statusCode = 500;
  let message = "Internal Server Error";
  let details = null;
  if (err instanceof prismaNamespace_exports.PrismaClientValidationError) {
    statusCode = 400;
    message = "Invalid input data or missing required fields.";
  } else if (err instanceof prismaNamespace_exports.PrismaClientKnownRequestError) {
    switch (err.code) {
      case "P2002":
        statusCode = 400;
        message = "Duplicate value found. This record already exists.";
        details = err.meta?.target;
        break;
      case "P2025":
        statusCode = 404;
        message = "Requested resource not found.";
        break;
      case "P2003":
        statusCode = 400;
        message = "Foreign key constraint failed.";
        break;
      case "P2014":
        statusCode = 400;
        message = "Invalid relation data.";
        break;
      case "P2016":
        statusCode = 400;
        message = "Query interpretation error.";
        break;
      default:
        statusCode = 400;
        message = "Database request error.";
    }
  } else if (err instanceof prismaNamespace_exports.PrismaClientUnknownRequestError) {
    statusCode = 500;
    message = "Unknown database error occurred.";
  } else if (err instanceof prismaNamespace_exports.PrismaClientInitializationError) {
    statusCode = 500;
    message = "Database connection failed.";
  } else if (err instanceof prismaNamespace_exports.PrismaClientRustPanicError) {
    statusCode = 500;
    message = "Critical database error.";
  } else if (err.name === "ZodError") {
    statusCode = 400;
    message = "Validation failed.";
    details = err.errors;
  } else if (err.message?.includes("Unauthorized")) {
    statusCode = 401;
    message = "Unauthorized access.";
  } else {
    message = err.message || message;
  }
  res.status(statusCode).json({
    success: false,
    message,
    error: process.env.NODE_ENV === "development" ? err : void 0,
    details
  });
};
var errorHandler_default = errorHandler;

// src/middlewares/notFound.ts
var notFound = (req, res) => {
  res.status(404).json({
    success: false,
    message: "Route not found",
    path: req.originalUrl
  });
};
var notFound_default = notFound;

// src/modules/category/category.route.ts
import express2 from "express";

// src/modules/category/category.service.ts
var createCategory = async (payload) => {
  return prisma.category.create({
    data: payload
  });
};
var getAllCategories = async () => {
  return prisma.category.findMany({
    orderBy: {
      createdAt: "desc"
    }
  });
};
var CategoryService = {
  createCategory,
  getAllCategories
};

// src/modules/category/category.controller.ts
var createCategory2 = catchAsync_default(async (req, res) => {
  const result = await CategoryService.createCategory(req.body);
  res.status(201).json({
    success: true,
    message: "Category created successfully",
    data: result
  });
});
var getAllCategories2 = catchAsync_default(async (req, res) => {
  const result = await CategoryService.getAllCategories();
  res.status(200).json({
    success: true,
    data: result
  });
});
var CategoryController = {
  createCategory: createCategory2,
  getAllCategories: getAllCategories2
};

// src/modules/category/category.route.ts
var router2 = express2.Router();
router2.post("/", auth_default("ADMIN" /* ADMIN */), CategoryController.createCategory);
router2.get("/", CategoryController.getAllCategories);
var CategoryRoutes = router2;

// src/modules/booking/booking.route.ts
import express3 from "express";

// src/modules/booking/booking.service.ts
var createBooking = async (payload, userId) => {
  return prisma.booking.create({
    data: {
      studentId: userId,
      tutorId: payload.tutorId,
      categoryId: payload.categoryId,
      message: payload.message,
      date: payload.date
    }
  });
};
var getMyBookings = async (userId) => {
  return prisma.booking.findMany({
    where: {
      studentId: userId
    },
    include: {
      tutor: true,
      category: true
    }
  });
};
var getTutorBookings = async (userId) => {
  return prisma.booking.findMany({
    where: {
      tutorId: userId
    },
    include: {
      student: true,
      category: true
    }
  });
};
var getBookingById = async (id) => {
  return prisma.booking.findUnique({
    where: { id },
    include: {
      student: true,
      tutor: true,
      category: true
    }
  });
};
var updateBookingStatus = async (id, status) => {
  return prisma.booking.update({
    where: { id },
    data: { status }
  });
};
var BookingService = {
  createBooking,
  getMyBookings,
  getTutorBookings,
  getBookingById,
  updateBookingStatus
};

// src/modules/booking/booking.controller.ts
var createBooking2 = catchAsync_default(async (req, res) => {
  const userId = req.user.id;
  const result = await BookingService.createBooking(req.body, userId);
  res.status(201).json({
    success: true,
    message: "Booking created successfully",
    data: result
  });
});
var getMyBookings2 = catchAsync_default(async (req, res) => {
  const userId = req.user.id;
  const result = await BookingService.getMyBookings(userId);
  res.status(200).json({
    success: true,
    data: result
  });
});
var getTutorBookings2 = catchAsync_default(async (req, res) => {
  const userId = req.user.id;
  const result = await BookingService.getTutorBookings(userId);
  res.status(200).json({
    success: true,
    data: result
  });
});
var getBookingById2 = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const result = await BookingService.getBookingById(id);
  res.status(200).json({
    success: true,
    data: result
  });
});
var updateStatus = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const { status } = req.body;
  const result = await BookingService.updateBookingStatus(id, status);
  res.status(200).json({
    success: true,
    message: "Booking status updated",
    data: result
  });
});
var BookingController = {
  createBooking: createBooking2,
  getMyBookings: getMyBookings2,
  getTutorBookings: getTutorBookings2,
  getBookingById: getBookingById2,
  updateStatus
};

// src/modules/booking/booking.route.ts
var router3 = express3.Router();
router3.post("/", auth_default("STUDENT" /* STUDENT */), BookingController.createBooking);
router3.get("/", auth_default("STUDENT" /* STUDENT */), BookingController.getMyBookings);
router3.get("/tutor", auth_default("TUTOR" /* TUTOR */), BookingController.getTutorBookings);
router3.get("/:id", auth_default(), BookingController.getBookingById);
router3.patch("/:id", auth_default("TUTOR" /* TUTOR */), BookingController.updateStatus);
var BookingRoutes = router3;

// src/modules/review/review.route.ts
import express4 from "express";

// src/modules/review/review.service.ts
var createReview = async (payload, userId) => {
  return prisma.review.create({
    data: {
      rating: payload.rating,
      comment: payload.comment,
      tutorId: payload.tutorId,
      bookingId: payload.bookingId,
      studentId: userId
    }
  });
};
var getTutorReviews = async (tutorId) => {
  return prisma.review.findMany({
    where: { tutorId },
    include: {
      student: {
        select: {
          id: true,
          name: true,
          image: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
};
var ReviewService = {
  createReview,
  getTutorReviews
};

// src/modules/review/review.controller.ts
var createReview2 = catchAsync_default(async (req, res) => {
  const userId = req.user.id;
  const result = await ReviewService.createReview(req.body, userId);
  res.status(201).json({
    success: true,
    message: "Review created successfully",
    data: result
  });
});
var getTutorReviews2 = catchAsync_default(async (req, res) => {
  const { tutorId } = req.params;
  const result = await ReviewService.getTutorReviews(tutorId);
  res.status(200).json({
    success: true,
    data: result
  });
});
var ReviewController = {
  createReview: createReview2,
  getTutorReviews: getTutorReviews2
};

// src/modules/review/review.route.ts
var router4 = express4.Router();
router4.post("/", auth_default("STUDENT" /* STUDENT */), ReviewController.createReview);
router4.get("/tutor/:tutorId", ReviewController.getTutorReviews);
var ReviewRoutes = router4;

// src/modules/admin/admin.route.ts
import express5 from "express";

// src/modules/admin/admin.service.ts
var getAllUsers = async () => {
  return prisma.user.findMany({
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      emailVerified: true,
      createdAt: true
    },
    orderBy: {
      createdAt: "desc"
    }
  });
};
var updateUserStatus = async (id, payload) => {
  return prisma.user.update({
    where: { id },
    data: payload
  });
};
var getAllBookings = async () => {
  return prisma.booking.findMany({
    include: {
      student: true,
      tutor: true,
      category: true
    },
    orderBy: {
      createdAt: "desc"
    }
  });
};
var AdminService = {
  getAllUsers,
  updateUserStatus,
  getAllBookings
};

// src/modules/admin/admin.controller.ts
var getAllUsers2 = catchAsync_default(async (req, res) => {
  const result = await AdminService.getAllUsers();
  res.status(200).json({
    success: true,
    data: result
  });
});
var updateUserStatus2 = catchAsync_default(async (req, res) => {
  const { id } = req.params;
  const result = await AdminService.updateUserStatus(id, req.body);
  res.status(200).json({
    success: true,
    message: "User updated successfully",
    data: result
  });
});
var getAllBookings2 = catchAsync_default(async (req, res) => {
  const result = await AdminService.getAllBookings();
  res.status(200).json({
    success: true,
    data: result
  });
});
var AdminController = {
  getAllUsers: getAllUsers2,
  updateUserStatus: updateUserStatus2,
  getAllBookings: getAllBookings2
};

// src/modules/admin/admin.route.ts
var router5 = express5.Router();
router5.get("/users", auth_default("ADMIN" /* ADMIN */), AdminController.getAllUsers);
router5.patch("/users/:id", auth_default("ADMIN" /* ADMIN */), AdminController.updateUserStatus);
router5.get("/bookings", auth_default("ADMIN" /* ADMIN */), AdminController.getAllBookings);
var AdminRoutes = router5;

// src/app.ts
var app = express6();
app.use(
  cors({
    origin: process.env.APP_URL || "http://localhost:3000",
    credentials: true
  })
);
app.use(express6.json());
app.all("/api/auth/*splat", toNodeHandler(auth));
app.use("/api/tutors", TutorProfileRoutes);
app.use("/api/categories", CategoryRoutes);
app.use("/api/bookings", BookingRoutes);
app.use("/api/reviews", ReviewRoutes);
app.use("/api/admin", AdminRoutes);
app.get("/", (req, res) => {
  res.send("SkillBridge API running...");
});
app.use(notFound_default);
app.use(errorHandler_default);
var app_default = app;

// src/index.ts
var index_default = app_default;
export {
  index_default as default
};
